### ISSUE TITLE
question: partial trace

### ISSUE THREAD

**Issue by titusnicolae** [gaogaotiantian/viztracer#101]
Hello!
Is it possible to interrupt viztracer profiling and get partial results?
Thanks

**Comment by gaogaotiantian** [comment]
I'm not 100% sure that I understood your question, but if you just Ctrl+C out of your script, VizTracer will save the report till that point.

**Comment by titusnicolae** [comment]
Apparently some combination of having started multiple processes and pressing multiple Ctrl-C didn't produce the html. I guess it's fine

**Comment by gaogaotiantian** [comment]
Oh, when it comes to multiple process, there are several things to consider:

* You can't just keep hitting Ctrl+C, you may exit the procedure of saving VizTracer log
* VizTracer needs to save the subprocess log first and combine them together. This should be automatic, but you probably need to make sure the subprocesses finish first. 
* ``subprocess`` module and ``multiprocessing`` module behave differently, so if you have further questions, please be more specific about the module you are using, the steps you've taken, and preferably a minimal test to reproduce what you've met.

**Comment by zplizzi** [comment]
Fwiw, I am using `multiprocessing` and the trace isn't getting written when I end the main process with ctrl-c. I don't have a handy reproduction unfortunately.

**Comment by gaogaotiantian** [comment]
> Fwiw, I am using `multiprocessing` and the trace isn't getting written when I end the main process with ctrl-c. I don't have a handy reproduction unfortunately.

Like I said above, the program needs to wait for the trace to be written from all the processes. If you somehow abrupted them, the trace file won't be written properly so you'll miss data. However, without a reproduction, there's nothing I can investigate at this point.
