### ISSUE TITLE
`json_tokenizer_failure` in Perfetto

### ISSUE THREAD

**Issue by gjoseph92** [gaogaotiantian/viztracer#106]
Importing the JSON output fails in Perfetto, showing something like this:

![Screen Shot 2021-04-06 at 6 29 22 PM](https://user-images.githubusercontent.com/3309802/113793669-13a35000-9706-11eb-95aa-ce7c5b6ef54d.png)

Here's the JSON produced by `viztracer -o test.json vt-test.py`:
https://gist.github.com/gjoseph92/f5c21ad1b328c8bed3e472be92a32342

And the contents of `vt-test.py` (tried a few different scripts; doesn't seem to matter):
```python
x = 0
for i in range(10000):
    x += 1
```

Note that the JSON loads fine in catapult.

I've replicated this with `viztracer==0.11.4`, `viztracer==0.12.0`, `viztracer==0.12.1`, `viztracer==0.12.2`, `viztracer==0.12.3`. 

The fact that it replicates even with older versions makes me think it's a Perfetto issue, but I wanted to open the issue here first in case anyone has seen this before, or it's an issue with viztracer's formatting of the JSON. If it's not viztracer's problem, I'm happy to move this to https://github.com/google/perfetto/issues

System:
* macOS 11.2 (x86)
* Python 3.8.8

**Comment by gaogaotiantian** [comment]
This is a perfetto bug and I've filed it in https://github.com/google/perfetto/issues/119

**Comment by gjoseph92** [comment]
Thanks! Sorry I didn't see that one. Feel free to close if you'd like (or leave open until the upstream issue is fixed, so others searching can find this?)

**Comment by gaogaotiantian** [comment]
I'll close it when perfetto is fixed. Thanks for submitting the issue, this would be helpful for other people having the same problem!

**Comment by gjoseph92** [comment]
As a hack, this has been working for me to drop the fractional timestamps and make the traces work around the current Perfetto bug:

```
$ jq "{traceEvents: [.traceEvents | .[] | (select(.ts) | .ts) |= round ]}" trace.json > trace-rounded.json
$ vizviewer trace-rounded.json
```

**Comment by gaogaotiantian** [comment]
BTW is there a reason that you prefer perfetto to catapult? VizTracer is in a transition phase so I would love to know how people think about those visualization tools

**Comment by gjoseph92** [comment]
Perfetto seems faster on large traces. Plus, it's a lot easier to navigate the UI (scrolling does what you expect, pinch-to-zoom works) compared to the switch-mouse-modes of catapult. Also the SQL integration could theoretically be useful?

Personally I actually like https://www.speedscope.app/ far more: the left-heavy view + aggregate statistics when you click on each trace are great for quickly making sense of a profile. (The main downside is not being able to show multiple threads/processes at once.) [In theory](https://github.com/jlfwong/speedscope/wiki/Importing-from-custom-sources#google-trace-event-format) speedscope should support Chrome-style traces out of the box, but it hangs/crashes whenever I try to use a VizTracer profile, and I haven't looked into it much.

**Comment by gaogaotiantian** [comment]
Okay Perfetto is definitely faster on large traces, and that is actually the reason I started considering to move to it. I don't think speedscope is designed for large trace. I can load light VizTracer trace with it. Maybe it just runs out of memory on large traces. I don't think it was optimized as much as Perfetto to handle GB level traces. I think, from Perfetto developers, Perfetto is working on FlameGraphs from trace, which I guess is pretty much the same thing as "left-heavy view". 

As for VizTracer, multi-process and multi-thread visualization is a very very important, if not the most important feature. There are plenty of profilers in the market, but few solves concurrency problems as VizTracer does. So I guess for now, I probably won't use speedscope as an official front-end :)

Well let's hope Perfetto could fix the floating point issue soon to save you a step to visualize traces :)

**Comment by gjoseph92** [comment]
Totally agreed that concurrency visualization is the key feature, so using a frontend that supports that well makes more sense.

FWIW Speedscope has handled ~600MB traces for me with great performance, so I do think it could handle it. But I'm seeing something like this (10000 more times) loading a 60MB VizTracer profile, so I think it's a format issue:
![Screen Shot 2021-04-07 at 9 52 33 PM](https://user-images.githubusercontent.com/3309802/113966647-b6ce9500-97ec-11eb-8739-e0a04c6a8008.png)
But yes, shouldn't be a priority to get it working (and might be a speedscope issue).

**Comment by gaogaotiantian** [comment]
Hmm, I think that's probably a timestamp overlap issue which I tried to solve a couple of versions before. Not sure if it's completely fixed. It could also be the way speedscope handles the data is different than catapult or perfetto. 

Anyways, making it work on speedscope is not a high priority now and I'll try to support Perfetto better.

**Comment by kllp** [comment]
@gjoseph92 your workaround works fine in most cases. Be aware that events are written on top of each other if they have the same rounded time. 
I hope the perfetto developers can fix this issue soon.

**Comment by gaogaotiantian** [comment]
I believe Perfetto fixed this in mainline code. I think it worked in Canary version now, but not Stable. I don't believe they will merge this fix back to Stable because VizTracer is not their priority :( . However, if you really need Perfetto instead of Catapult, you can use Canary version now. I'll leave this issue open until stable version works.

**Comment by gaogaotiantian** [comment]
@gjoseph92 I wanted to tell you that the negative duration bug is fixed. Also the latest VizTracer comes with a customized local Perfetto that you can simply run by ``vizviewer result.json``. Let me you if you have the chance to try it.
