### ISSUE TITLE
Question: How to remove the start offset when combining traces?

### ISSUE THREAD

**Issue by kllp** [gaogaotiantian/viztracer#107]
Usually you combine traces from the same parallel execution run.
For comparison it could be useful to see different sequential runs below each other without a start offset.
How can I start every trace at 0 seconds with `viztracer --combine`?

**Comment by gaogaotiantian** [comment]
Currently it's not possible to do this(directly with VizTracer). Synchronizing traces from different run might be a useful feature. I'll see how I could proceed on this.

You can also change the timestamp of the json file by yourself(or even write a plugin for it) if you need this feature asap.

**Comment by gaogaotiantian** [comment]
Hi @kllp , I added the feature in master so you can combine reports with ``--align_combine`` and all the reports will be aligned from the start. I probably won't release it immediately, so you can install from git ``pip install git+https://github.com/gaogaotiantian/viztracer``. Let me know if this works for you.

**Comment by kllp** [comment]
It works! Thank you so much @gaogaotiantian! You made my day!
