### ISSUE TITLE
Timeunit is off by 1000x

### ISSUE THREAD

**Issue by gaogaotiantian** [gaogaotiantian/viztracer#111]
Should've used us instead of ms for time unit display

**Comment by lucasleesw** [comment]
Hi, I met the error below, I think it might be caused by this issues.
```
While importing:
Error: Unit us is not supported.
    at TraceEventImporter.storeDisplayTimeUnit_ (chrome://tracing/tracing.js:6336:495)
    at new TraceEventImporter (chrome://tracing/tracing.js:6272:90)
    at Import.createImporter_ (chrome://tracing/tracing.js:2023:8)
    at chrome://tracing/tracing.js:2015:167
    at Task.run (chrome://tracing/tracing.js:3266:95)
    at runAnother (chrome://tracing/tracing.js:3269:371)
    at runTask (chrome://tracing/tracing.js:3031:57)
    at processIdleWork (chrome://tracing/tracing.js:3036:116)
    at window.requestIdleCallback.timeout (chrome://tracing/tracing.js:3029:81)
```

**Comment by gaogaotiantian** [comment]
Hi @lucasleesw , thanks for submitting the issue.

This is a bug that I will fix today. However, fixing the bug does not fix the underlying issue(which was the cause of this bug) - Perfetto is not fully backward-compatible with the Catapult trace viewer(which is what chrome://tracing is).

Could you tell me why are you using chrome://tracing instead of ``vizviewer`` or Perfetto, or the HTML output which is actually legacy UI. In my point of view, chrome://tracing has no advantage now.

For many reasons, we are transitioning to Perfetto(``vizviewer``) from Catapult trace viewer, and I'll try to make the transition as smooth as possible. But if there is a compatibility issue, you should expect the ``json`` file works on Perfetto, not Catapult trace viewer(chrome://tracing).

In the future when everything is mature, I'll probably move chrome://tracing out of supported tools unless I can make it reasonably work and there's a good reason to leave it there.

Please let me know if you have more problems!

**Comment by lucasleesw** [comment]
Thanks for your detailed response. I change the version to 0.12.0 and every thing works fine for me. You are right that I could give up chrome://tracing and tune to vizviewer. I think the only reason is that the viztracer is installed in the server and I want to check the trace in my personal computer without connection to the server. But in this case HTML output should works fine as well and I will try that. Thank you again for your valuable explanation.

**Comment by gaogaotiantian** [comment]
@lucasleesw I would not recommend using an old version, as there might be known bugs. However, if an older version works for you, it's totally up to you if you want to use that. Just keep in mind that, as of now, there won't be any bug fixes merging back to old version.

It's a valid reason that you want to open the report on your personal computer. There are a couple of suggestions:

* Use https://ui.perfetto.dev instead of chrome://tracing
* Install ``viztracer`` locally and use ``vizviewer`` to view the json report generated from the server
* As you said, use HTML output, even though it would be MB-level larger than json file

Hope this answers your question!
