### ISSUE TITLE
doc have a mistake

### ISSUE THREAD

**Issue by ziliangok** [gaogaotiantian/viztracer#13]
https://viztracer.readthedocs.io/en/stable/advanced_usage.html

tracer = VizTracer(include_files=["./src"])
Similarly, you can exclude certain files/folders to trace by

viztracer --exclude_files ./not_interested.py --run my_script.py
OR

tracer = VizTracer(**include_files**=["./not_interested.py"])

这里错啦。
项目不错。

**Comment by gaogaotiantian** [comment]
Fixed in master, thanks!
