### ISSUE TITLE
stale documentation

### ISSUE THREAD

**Issue by tomasohara** [gaogaotiantian/viztracer#134]
Thanks for making viztracer available. Note that the documentation is stale (e.g., several references to result.html being the default). It seems that the .rst files need to be regenerated from the source.

via https://viztracer.readthedocs.io/en/stable/viztracer.html:
      classVizTracer(self, tracer_entries=1000000, ..., output_file='result.html')

Best,
Tom

**Comment by gaogaotiantian** [comment]
Fixed. Will merge in later in case there are more problems :)
