### ISSUE TITLE
document object types

### ISSUE THREAD

**Issue by tomasohara** [gaogaotiantian/viztracer#135]
Hi, there doesn't seem to be documentation on the traced object types. This came up when I was trying to explain the JSON output to a colleague (e.g., example 1 below).

Documentation on the field names shown in the trace would also be helpful (e.g., ph in exmaple 1 & 2 below).

Best,
Tom

-----

1. via json_pp of result.json:
      {
         "ph" : "X",
         "tid" : 23546,
         "ts" : 93650932092.354,
         "dur" : 6.938,
         "pid" : 23546,
         "name" : "removeEmptyStartAndEnd (auxiliary.py:368)",
         "args" : {
            "return_value" : "['moe']",
            "func_args" : {
               "content" : "['moe', '']"
            }
         },
         "cat" : "FEE"
      },

2. via snaptrace.c:

$ egrep '(case.*NODE)|("ph")|("\w")' ./src/viztracer/modules/snaptrace.c                                                                
    PyObject* ph_B = PyUnicode_FromString("B");         /* TPO: unused */
    PyObject* ph_E = PyUnicode_FromString("E");         /* TPO: likewise */
    PyObject* ph_I = PyUnicode_FromString("i");
    PyObject* ph_X = PyUnicode_FromString("X");
    PyObject* ph_C = PyUnicode_FromString("C");
    PyObject* ph_M = PyUnicode_FromString("M");
        PyDict_SetItemString(dict, "ph", ph_M);
        PyDict_SetItemString(dict, "ph", ph_M);
        case FEE_NODE:
            PyDict_SetItemString(dict, "ph", ph_X);
        case INSTANT_NODE:
            PyDict_SetItemString(dict, "ph", ph_I);
            PyDict_SetItemString(dict, "s", node->data.instant.scope);
        case COUNTER_NODE:
            PyDict_SetItemString(dict, "ph", ph_C);
        case OBJECT_NODE:
            PyDict_SetItemString(dict, "ph", node->data.object.ph);
        case RAW_NODE:
            PyDict_SetItemString(dict, "ph", ph_M);
        // The documentation did not say whether the value persists on "s"
    if (!PyArg_ParseTuple(args, "O", &raw)) {
        if (!PyArg_ParseTuple(args, "l", &self->buffer_size)) {

**Comment by gaogaotiantian** [comment]
The JSON format is chrome trace format, you can refer to the official docs - https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview

**Comment by tomasohara** [comment]
Thanks for the prompt reply.

Note that I found other documentation-related issues not significant enough
to warrant of a ticket:
- my_sciprt.py => [my_scriprt.py]
- "logging.basicConfig(handlers = [handler]"--missing ending parenthesis

Best,
Tom

**Comment by gaogaotiantian** [comment]
Thank you for finding these problems in the docs, and letting me know people are looking at the docs :)

I have started a PR for docs fixing and have fixed the problems you mentioned. I'll leave it there for a couple of days in case there are more issues you find later.
