### ISSUE TITLE
Async support

### ISSUE THREAD

**Issue by devova** [gaogaotiantian/viztracer#15]
Does it support async python? Does it use cProfile under the hood or use yappi which can deal with async Python?

**Comment by gaogaotiantian** [comment]
It uses neither cProfile nor yappi. VizTracer implements its own function hook to capture the FEE. 

It works with async, there's no reason it's not working. I have tried simple cases and viztracer did not stop python from working. However, whether it's "working for you" depends on what feature do you expect from it. 

In theory, "async python" is just an advanced grammar in python. There's a scheduler running on single thread and doing the async tasks. What you'll be able to observe in viztracer is the whole scheduler loop mechanism, which means even the simplest async program will generate a rather complicated trace, which shows how python deals with async functions in its way.

So, if you mean, "if I could use viztracer on async programs", the answer is yes. If you want an "async view" which could hide all the python internal mechanism under the carpet, the answer would be no.

**Comment by gaogaotiantian** [comment]
I just took a look at https://github.com/sumerc/yappi/blob/master/doc/coroutine-profiling.md and I think this might be the thing you are talking about.

If you are asking for whether viztracer calculates async function when it's "await", the answer is no. Just like cProfile, viztracer is based on how python actually works. 

As for the feature Yappi provides, personally I kind of disagree. The point of async functions is to be able to do other stuff when the function is "waiting" for others to finish. Counting the CPU time when it's in "await" state does not add up to me. 

I think a very similar analogy would be bandwidth vs latency. These are two measures for any communication. cProfile profiles async functions for their "bandwidth", aka how much CPU time they actually consume, while yappi profiles based on "latency", aka when this function can return its' value.
