### ISSUE TITLE
oops!Your WASM trace processor ran out of memory!

### ISSUE THREAD

**Issue by JiangFHao** [gaogaotiantian/viztracer#157]
curl -LO https://get.perfetto.dev/trace_processor
chmod +x ./trace_processor
trace_processor --httpd /path/to/trace.pftrace
# Reload the UI, it will prompt to use the HTTP+RPC interface

**Comment by gaogaotiantian** [comment]
What's this issue about? This is not related to viztracer

**Comment by gaogaotiantian** [comment]
Please reopen this issue and be more specific about the problem if this is about viztracer
