### ISSUE TITLE
Subprocess injection mechanism gaps make it impossible to try tracing pip's behaviour

### ISSUE THREAD

**Issue by pradyunsg** [gaogaotiantian/viztracer#160]
I think the title covers my usecase. :)

In a clean virtualenv, install viztracer, and then run:

```
viztracer -m pip install --debug requests --no-binary :all:
```

You'll notice that all of pip's subprocess calls will fail:

```
  ERROR: Command errored out with exit status 2:
   command: /Users/pradyunsg/Developer/pip/.venv/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/y1/j465wvf92vs938kmgqh63bj80000gn/T/pip-install-z2tj4fa8/requests_82de87b5220c4e10809d513d90ca41a5/setup.py'"'"'; __file__='"'"'/private/var/folders/y1/j465wvf92vs938kmgqh63bj80000gn/T/pip-install-z2tj4fa8/requests_82de87b5220c4e10809d513d90ca41a5/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/y1/j465wvf92vs938kmgqh63bj80000gn/T/pip-pip-egg-info-0gaf3f7n
       cwd: /private/var/folders/y1/j465wvf92vs938kmgqh63bj80000gn/T/pip-install-z2tj4fa8/requests_82de87b5220c4e10809d513d90ca41a5/
  Complete output (5 lines):
  
  Usage:
    /Users/pradyunsg/Developer/pip/.venv/bin/python -m pip <command> [options]
  
  no such option: -c
  ----------------------------------------
```

**Comment by gaogaotiantian** [comment]
I’ll take a look into it, but to clarify, do you want a way to disable the subprocess instrumentation, or you actually need the subprocesses trace?

**Comment by pradyunsg** [comment]
Thank you! ^>^

Having tracing for subprocesses would be nice, since pip can call subprocesses of itself and other projects, in isolated build environment or the current environment. It also sometimes zips itself up, and calls a Python process to running that zip in an isolated build environment. It would definitely be useful to get the numbers on how "expensive" each of these is.

However, it's also fine to not have that though, and to be able to see the main running process would still be an improvement. :)

**Comment by gaogaotiantian** [comment]
You can try ``--ignore_multiprocess`` to see if it'll work. That's the option to turn off the instrumentation for ``multiprocessing`` and ``subprocess``.

In the meantime, I'll investigate if adding ``-c`` option for viztracer can fix this.

**Comment by pradyunsg** [comment]
You’ll need the latest release of pip for that. None the less, that is mostly a no-op unless a runtime exception occurs (it basically disables the top level try-except block).

**Comment by pradyunsg** [comment]
I don’t think there’s any way to NOT fiddle around with the environment. You should be able to tack on a pip uninstall to reset the environment though.

I’ll post proper instructions tomorrow — it’s almost 1am in my part of the world.

**Comment by gaogaotiantian** [comment]
Okay I think I successfully reproduced it myself and found the problem. ``viztracer`` tries to replace ``python`` in ``subprocess`` instrumentation, but ``python`` has some less used arguments, for example, ``-c``, that ``viztracer`` did not implement. I added the ``-c`` support in #161 and some other stuff to adapt to python. It works for me now with the ``subprocess`` instrumentation. You can try it with the master branch - ``pip install git+https://github.com/gaogaotiantian/viztracer``(I guess you are the expert of using pip, just in case). 

Also, maybe it's worth it to try the ``--ignore_multiprocess`` option to see if that works for you :)
