### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte

### ISSUE THREAD

**Issue by quantumdot** [gaogaotiantian/viztracer#173]
Hi,

Trying out this library for its multiprocessing support over `cProfile`. I ran my program as described in the docs:
```
viztracer cli.py --additional-args
```
Tracing seems to run fine and reports 7000034 entries total and generates a json file ~1GB in size. But when I go to open the report, a la `vizviewer result.json`, I receive the following error and stack trace:
```
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\envs\my-env\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\anaconda3\envs\my-env\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\anaconda3\envs\my-env\Scripts\vizviewer.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\anaconda3\envs\my-env\lib\site-packages\viztracer\viewer.py", line 175, in viewer_main
    ret_code = view(
  File "C:\Users\user\anaconda3\envs\my-env\lib\site-packages\viztracer\viewer.py", line 123, in view
    trace_data = json.load(f)
  File "C:\Users\user\anaconda3\envs\my-env\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\user\anaconda3\envs\my-env\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1072792661: character maps to <undefined>
```
Please advise how to correct. Thanks!

**Comment by gaogaotiantian** [comment]
Hi,

This is a bug for ``vizviewer``. I assume that there are unicode characters in your program(that are not ascii)? The default encoding on Windows is not utf-8 which was the reason of this issue.

I fixed it in report builder but forgot the viewer, thanks for catching it.

I plan to fix this in master today, and the release will come a bit after. You should be able to test with the master branch when I fix it.

**Comment by gaogaotiantian** [comment]
Actually, could you give me the code(preferably a small example) that you used for the issue? I'd like to reproduce it locally.

**Comment by quantumdot** [comment]
Thanks for the quick response!

> I assume that there are unicode characters in your program(that are not ascii)? The default encoding on Windows is not utf-8 which was the reason of this issue.

Hmm, not that I know of, but possible an imported library has non-ascii characters? I'm pretty confident that all of my source files have an encoding of UTF-8, and I generally don't use non-ascii characters. I working in python 3.8 if that matters at all.

> could you give me the code(preferably a small example) that you used for the issue?

Might be difficult to share the code. The repo is private and the application is not trivial to setup (deep learning platform for processing data). I can share the `results.json` file with you privately if that will help!

**Comment by gaogaotiantian** [comment]
Hi,

If the code is private and can't be abstracted to a small example, then don't bother doing it. The json file would be too huge to share.

I checked in the fix(that I thought) in master, could you try that by ``pip install git+https://github.com/gaogaotiantian/viztracer``? If it does not work, please reopen this issue and I'll investigate what happened.
