### ISSUE TITLE
don't hard-code the port number

### ISSUE THREAD

**Issue by brandondube** [gaogaotiantian/viztracer#183]
Thanks for this great tool.  I was trying to compare two programs side-by-side running vizviewer, but was struck by `OSError: [Errno 48] Address already in use`.  It should be easy to retry by bumping up the port number until the error no longer occurs (maybe max out at, say, 10 tries)

**Comment by gaogaotiantian** [comment]
When you use the Python built-in http server ``python -m http.server``, it will host an http server on port 8000 by default. If you run the command in another terminal, it will report the same error. The correct way(or the way Python maintainers believes) is to do an explicit port assignment ``python -m http.server 8001``.

I also think explicit is better than inexplicit. Heuristics sometimes work well, and maybe in this case.

However, for now I will keep the way it is, and you can specify the port number explicitly with ``vizviewer result.json -p 9002``.

Actually, there's another interesting way to compare two programs side by side. Try the ``--align_combine`` command.

Say you have two reports - ``result1.json`` and ``result2.json``. Do ``viztracer --align_combine result1.json result2.json -o combined_result.json``.

``viztracer`` will combine two reports into one and align them. This is especially helpful if you are running a single-process program, in which case you'll see two processes displayed with an aligned start.

**Comment by brandondube** [comment]
Thanks -- I didn't realize it was just `http.server` under the hood.  Your fix works and is plenty simple enough.  I'll keep the align_combine use in mind for the future, but the particular pair of things I was looking at this time are dissimilar (the same variety of program, but different problems completely), so aligning them in time wouldn't make any sense.

**Comment by gaogaotiantian** [comment]
Well, it's not entirely ``http.server`` under the hood. I used that as an example of design decisions :). However, ``vizviewer`` is hosting an http server and that's the basic structure, so it's comparable. I'm glad things worked out for you!
