### ISSUE TITLE
cannot install viztracer

### ISSUE THREAD

**Issue by Stevenyyi** [gaogaotiantian/viztracer#2]
I upgraded pip and virtualenv to latest version. but still cannot download the viztracer. see the errror below:
 
(env) yangyi@yangyis-mac bin % python -m pip install viztracer
ERROR: Could not find a version that satisfies the requirement viztracer (from versions: none)
ERROR: No matching distribution found for viztracer

**Comment by Stevenyyi** [comment]
By the way, my python version (env) 
yangyi@yangyis-mac bin % python --version
**Python 3.7.3**

**Comment by gaogaotiantian** [comment]
Hi,

The fact is, we have never officially supported MacOS before 0.1.2. However, we started to do so from 0.1.3, which is just released. Binary package is provided through pip and fallback source tar is uploaded as well. 

We also started validating it on github's MacOS VM. 

So just install the latest version and you should be able to use it.

Thanks

**Comment by Stevenyyi** [comment]
cool! thank you Tian. It works now. Closed the issue.
