### ISSUE TITLE
KeyError: viztracer_metadata

### ISSUE THREAD

**Issue by nicelhc13** [gaogaotiantian/viztracer#208]
Hi,
First, thank you for your awesome work!

I am using Python 3.8.11, and am trying to get profiling with GIL (by following this article): https://www.maartenbreddels.com/perf/jupyter/python/tracing/gil/2021/01/14/Tracing-the-Python-GIL.html)

I did the following commands:
```
$ perf record -e sched:sched_switch  -e sched:sched_process_fork -e 'sched:sched_wak*' -k CLOCK_MONOTONIC  --call-graph dwarf -- viztracer -o viztracer1-gil.json --ignore_frozen [MY PYTHON SCRIPT COMMAND]
$ perf script --no-inline | per4m perf2trace sched -o perf1-state.json
$ viztracer --combine perf1-state.json viztracer1-gil.json -o example1-gil.html
```
The above two commands correctly produced outputs.
But, when I tried the last command, it gave me this error:
```
Dumping trace data, total entries: 103120Traceback (most recent call last):                                                                                                                                 
  File "[PATH]/viztracer", line 8, in <module>                       
    sys.exit(main())                                                                                                                                                                                        
  File "[PATH]/python3.8/site-packages/viztracer/main.py", line 594, in main
    success, err_msg = ui.run()                                                                                                                                                                  
  File "[PATH]/python3.8/site-packages/viztracer/main.py", line 345, in run
    return self.run_combine(files=self.options.combine)                                                                                      
  File "[PATH]/python3.8/site-packages/viztracer/main.py", line 458, in run_combine
    builder.save(output_file=ofile)                                                                                                                                                                         
  File "[PATH]/python3.8/site-packages/viztracer/report_builder.py", line 177, in save                              
    self.generate_report(f, output_format="html", file_info=file_info)                                                                                 
  File "[PATH]/python3.8/site-packages/viztracer/report_builder.py", line 148, in generate_report
    self.prepare_json(file_info=file_info, display_time_unit="ns")                                                                                                                                         
  File "[PATH]/python3.8/site-packages/viztracer/report_builder.py", line 112, in prepare_json
    if self.combined_json["viztracer_metadata"].get("overflow", False):                                                                                                                                     
KeyError: 'viztracer_metadata'                                                                
                                                                                             
```
So I removed lines touching `viztracer_metadata` keys from `report_builder.py` and could get outputs.
Is this a bug or am I missing something here?

FYI, I could see `viztracer_metadata` from viztracer1-gil.json file.

**Comment by gaogaotiantian** [comment]
Could check `perf1-state.json` to see if there's ``viztracer_metadata`` key in it? I think the reason is that ``perf1-state.json`` is generated by ``per4m``, which is Maarten's 3rd-party tool as a supplement to VizTracer. Cool as the tool is, it was built a while ago and VizTracer has stepped forward quite a long distance.

In short, VizTracer expects the input reports(json files) to not only be a valid json, a valid Chrome Trace Event file, but a VizTracer generated file. There could be some work done there to make it as compatible as possible, and I will look into that to see if it's worth it.

There are a couple of options for you at the moment.
1. Obviously, you can edit the viztracer locally just to remove that line, that could just work in your case.
2. Pin your viztracer to the version Maarten used for this project, when there's no such requirement.
3. Added the ``viztracer_metadata`` key in the json either manually or with code to make ``viztracer`` happy.

Also, if you do decide to use the up-to-date VizTracer, I would suggest that you use ``json`` as the final output and use ``vizviewer`` to display the report. It was much better than the ``html`` version. The ``html`` version is kind of deprecated now.

You can do:
```
$ viztracer --combine perf1-state.json viztracer1-gil.json -o example1-gil.json
$ vizviewer example1-gil.json
```

**Comment by nicelhc13** [comment]
Thank you for your fast response.
`perf1-state.json` does not contain that key. So it makes sense to me.
I will stick with the first option.

I have another question. (I am sorry to ask this question on this issue even though it is different from the main topic)
I am now using json format with vizviewer. This is awesome!!
But is this viewer using browser?

My actual workloads are more complex and generate a big log file.
Its size is few hundreds of MBs or few GBs, and the browser (firefox) keeps failining to open it.

FYI, this is command that I used:
```$ vizviewer output.json ```
and the error is:
```
Trace: http://127.0.0.1:9001/localtrace
Viewed on: http://127.0.0.1:9001

Error: RPC framing error
```
I guess this is because of OOM on browser.

**Comment by nicelhc13** [comment]
I noticed that it is using `Perfetto`  and found a way from here: https://perfetto.dev/docs/visualization/large-traces

Please feel free to close this issue.

Again, thank you for your awesome work and immediate helps!

**Comment by gaogaotiantian** [comment]
It is known that Firefox does perform as well as Chrome for Perfetto on large traces. (Not hard to imagine huh? It's built by Google.) Anything < 1GB should be reasonably for Chrome. However, you can definitely use local Perfetto trace processors if you like, and if you don't need the fancier features of the vizviewer customized version - for example, source code display on the functions.

I will close this issue for now, but feel free to ask other questions.
