### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by vincehex** [gaogaotiantian/viztracer#209]
![image](https://user-images.githubusercontent.com/35105162/155945510-21c65eac-6801-430b-8023-a2e383c8e300.png)
![image](https://user-images.githubusercontent.com/35105162/155945905-dacd3aff-0bef-4d87-b3eb-38703131e046.png)
安装时候，Python 3.6.8版本安装失败，请问是怎么回事？

**Comment by gaogaotiantian** [comment]
这个介于bug和非bug之间。

根本原因是我在换Release的CI的时候，直接用了他们的设置，所以把3.6的wheels给漏掉了……就导致你3.6只能从tar开始安装，然后就需要一定的环境。这理论上是我的疏忽，我打算修复。

但是从另一个角度说，python3.6在去年年底的时候EOL了，官方已经不再认为它是一个要继续维护的版本了，所以还是建议你用更高版本的python。
