### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by 978326187** [gaogaotiantian/viztracer#21]
i try to run `python -m viztracer --include_files ./config train.py --settings_file config/settings.yaml`
but get error: **python -m viztracer: error: unrecognized arguments: --settings_file**
it seems like the parameters between viztracer and train.py is misunderstand, how can i solve this problem?

**Comment by gaogaotiantian** [comment]
```include_files``` takes any number of arguments, which could potentially introduce ambiguity. If you take a look at the [docs](https://viztracer.readthedocs.io/en/latest/advanced_usage.html#filter), ```--run``` is used to resolve the ambiguity. 

In your case, use  ```python -m viztracer --include_files ./config --run train.py --settings_file config/settings.yaml``` instead

**Comment by 978326187** [comment]
> `include_files` takes any number of arguments, which could potentially introduce ambiguity. If you take a look at the [docs](https://viztracer.readthedocs.io/en/latest/advanced_usage.html#filter), `--run` is used to resolve the ambiguity.
> 
> In your case, use `python -m viztracer --include_files ./config --run train.py --settings_file config/settings.yaml` instead

Actually，i have tried this method, the same error is reported.
![image](https://user-images.githubusercontent.com/29019279/95669838-708ad700-0bb7-11eb-95b1-c0ac11debd91.png)

**Comment by gaogaotiantian** [comment]
This is a valid bug and I will try to fix it ASAP.

**Comment by gaogaotiantian** [comment]
Hi,

I think I fixed the argument parsing issue on #22 . I will make a release recently including this fix. In the mean time, if you want to test the fix, you can clone the repo, build & install it manually.

```
git clone https://github.com/gaogaotiantian/viztracer.git
cd viztracer
# Use make file directly.
make
# Or make it transparent
pip uninstall -y viztracer # uninstall old version
python setup.py build # build
python setup.py install # install
```

**Comment by 978326187** [comment]
i successfully run my command. thank you very much!

**Comment by gaogaotiantian** [comment]
Glad to hear it! Hope you enjoy VizTracer!
