### ISSUE TITLE
TypeError: view() got an unexpected keyword argument 'once'  

### ISSUE THREAD

**Issue by ichobits** [gaogaotiantian/viztracer#215]
python 3.8
jupyter notebook
viztracer 0.15.0

TypeError: view() got an unexpected keyword argument 'once' 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\anaconda3\lib\site-packages\viztracer\cellmagic.py in <lambda>(b)
     21 
     22             button = Button(description="VizTracer Report")
---> 23             button.on_click(lambda b: server.view(file_path, once=True))
     24 
     25             display(button)

TypeError: view() got an unexpected keyword argument 'once'

**Comment by gaogaotiantian** [comment]
Duplicated as #213 , already fixed in master and will be release soon
