### ISSUE TITLE
--log_async 跟踪协程时，左侧Task-xxx的顺序是不规则的

### ISSUE THREAD

**Issue by lijiachang** [gaogaotiantian/viztracer#222]
viewer左侧导航，Task 列表没有规律，在大量Task的时候，能以寻找

**Comment by lijiachang** [comment]
![Snipaste_2022-04-01_18-16-57](https://user-images.githubusercontent.com/28041718/161244874-064b49eb-22d2-4268-827b-a22f58145b64.png)

**Comment by gaogaotiantian** [comment]
首先，这个应该是Perfetto的内容，也就是VizTracer用的前端。然后我印象中Task应该是按照建立顺序排列的。我不是100%确定了。如果它确实是随机排列的，VizTracer这边也很难做任何改动去改变这个属性……
