### ISSUE TITLE
请问: 想在程序里面跟踪某个函数里的所有变量该怎么做呢?

### ISSUE THREAD

**Issue by jumbojing** [gaogaotiantian/viztracer#223]
请问: 想在程序里面跟踪某个函数里的所有变量该怎么做呢?

**Comment by gaogaotiantian** [comment]
你需要定义“跟踪”这个概念。这不是一个定义清晰的概念。

你有若干个选择，首先可以考虑把函数里的变量变成`VizObject`或者`VizCounter`，好处是当你写入它们的attribute的时候，会自动trigger一个记录。坏处就是，你变量的实际类型改变了，你需要比较大规模地修改代码，相当于给你的变量多了个wrapper。

或者你可以手动log你的变量，用`log_var`。好处是你原来的逻辑结构是完全不用变的，你只需要增加一个log点，坏处就是你需要知道在哪里log，它不会变量一变就自动log。

VizTracer本身并不是设计给“跟踪变量”这个功能的，如果你真的想做比较全面的“跟踪变量”，建议你看一下https://github.com/gaogaotiantian/watchpoints，它才是专门拿来跟踪变量的。

**Comment by jumbojing** [comment]
这样行不行呢?将watchpoints作为viztracer的插件, 或者将二者结合起来...

**Comment by gaogaotiantian** [comment]
你可以两个一起用，理论上说可以通过callback实现这件事。但是watchpoints的overhead非常大，因为用的是settrace，而viztracer的一个很重要的理念是低overhead，所以对于VizTracer本身来说，引入watchpoints是一个背离核心理念的事。

把它们俩结合起来用也不是那么难，你完全可以自己尝试一下。但是你自己得意识到，watchpoints是“追踪变量”用的，它是单纯的一个debugging tool，一旦引入了watchpoints，你的profiling，也就是判断函数运行时长的内容，就毫无价值了。

**Comment by jumbojing** [comment]
这个log_var在`Inline`里, 我想trace所有的变量, 比如用:
```
from viztracer import VizTracer

tracer = VizTracer()
tracer.log_var(?????)
tracer.start()
# Something happens here
tracer.stop()
tracer.save() 
```
能不能用正则表达式呢?咋用呀?

**Comment by gaogaotiantian** [comment]
就像我前面说的，viztracer并不是用来“追踪变量”的，所以你的用法是不正确的，你这种直觉的用法，是watchpoints的用法。viztracer没有内置的机制可以“追踪”变量，它只能“记录”变量，它无法感知到变量的改变（除非你使用VizObject之类的套一层）。

大致的用法是这样的：

```
from viztracer import VizTracer, get_tracer

def your_function():
    while True:
        a = get_a_value()
        get_tracer().log_var("a", a)

tracer = VizTracer()
tracer.start()
your_function()
tracer.stop()
tracer.save() 
```

也就是说，你需要自己知道自己的变量什么时候改变了，然后在改变之后去记录这个改变的变量。把VizTracer想象成一个可视化工具，而不是一个追踪变量的工具，这是watchpoints做的事情。

既然没有`trace`这个概念，自然也就谈不到“trace所有的变量”。你可以通过`locals()`这种builtin函数来拿到当前所有的局部变量，但是你不能"trace"它们，这不是VizTracer的功能。
