### ISSUE TITLE
协程中的任务展示问题，不知道是否正常

### ISSUE THREAD

**Issue by lijiachang** [gaogaotiantian/viztracer#224]
感谢您的回复！
首先我对这款工具能分析协程感到惊喜！

我在分析过程中发现，图中剪头处的空白，是否认为该协程Task交出了控制权？
按照我的理解，publish__XXX是函数是耗时的，应该交出了控制权，自动切换到其他协程任务。
**但是最上方紫色的consumer_worker一直没有断点（意为着改task一直在执行？）**
这让我感到很疑惑
![image](https://user-images.githubusercontent.com/28041718/161550176-324eea71-d9f5-442b-b2db-8ac39942f23e.png)

在其他协程中，我看到是符合预期的：即 执行到publish__XXX协程对象时，切换到其他协程任务
![image](https://user-images.githubusercontent.com/28041718/161552434-f57fe713-6cc4-4f4c-9e4f-ee260bf948a5.png)

你的粉丝敬上😁

**Comment by gaogaotiantian** [comment]
没有源代码很难去判断到底是什么原因，可能你代码写的本来就是这个样子的。比如是不是run的时候你就是`asyncio.run(consumer_worker())`了，那它自然是不会退出的。

**Comment by lijiachang** [comment]
> 没有代码源代码很难判断到底是什么，可能写的本来就是这个`asyncio.run(consumer_worker())`样子。

代码大概是这样，设计为 一个生产者，5个消费者
publish__XXX 由 self.dispatch_message(message) 调用

代码：
    async def consumer_worker(self, worker_id, queue):
        while True:
            message = await queue.get()
            try:
                await self.dispatch_message(message)
            except Exception as e:
                logger.exception(str(e), exc_info=True, stack_info=True)
            finally:
                queue.task_done()

    async def producer_worker(self, queue):
        async for message in self.websocket:
            await queue.put(message)

    async def handler(self):
        loop = asyncio.get_event_loop()
        message_queue = asyncio.Queue(maxsize=10000)
        consumers = [loop.create_task(self.consumer_worker(i, message_queue)) for i in range(5)]

        prod = loop.create_task(self.producer_worker(message_queue))

        await asyncio.wait(consumers + [prod])

**Comment by lijiachang** [comment]
> 没有代码源代码很难判断到底是什么，可能写的本来就是这个`asyncio.run(consumer_worker())`样子。

那如何才能让consumer_worker()协程里的任务，遇到await 也主动交出控制权呢

**Comment by lijiachang** [comment]
我理解遇到await一定会交出控制权才对？
怎么会出现连续的执行一个协程的情况

才疏学浅

**Comment by gaogaotiantian** [comment]
await不一定会交出控制权，要看你await的是什么东西。await一个task/future是一定会交出控制权的，但是await一个coroutine不会，它会call这个coroutine的内容。如果这个coroutine中没有任何东西阻碍它继续，就会一直运行。

给你个简单点的例子：
```
import asyncio

async def fake_async():
    return 1

async def endless_task():
    while True:
        await fake_async()

async def never_exec_task():
    print(1)

async def main():
    t1 = asyncio.create_task(endless_task())
    t2 = asyncio.create_task(never_exec_task())

    t1.join()
    t2.join()

if __name__ == "__main__":
    asyncio.run(main())

```

这个例子中，`endless_task`里是有`await`的，但是由于await的是一个coroutine，并且这个coroutine内部并没有任何交出控制权的机制，所以它会不停地运行，导致`never_exec_task()`永远无法运行。

**Comment by lijiachang** [comment]
> await不一定会交出控制权，要看你await的是什么东西。await一个task/future是一定会交出控制权的，但是await一个coroutine不会，它会call这个coroutine的内容。如果这个coroutine中没有任何东西阻碍它继续，就会一直运行。
> 
> 给你个简单点的例子：
> 
> ```python
> import asyncio
> 
> async def fake_async():
>     return 1
> 
> async def endless_task():
>     while True:
>         await fake_async()
> 
> async def never_exec_task():
>     print(1)
> 
> async def main():
>     t1 = asyncio.create_task(endless_task())
>     t2 = asyncio.create_task(never_exec_task())
> 
>     t1.join()
>     t2.join()
> 
> if __name__ == "__main__":
>     asyncio.run(main())
> ```
> 
> 这个例子中，`endless_task`里是有`await`的，但是由于await的是一个coroutine，并且这个coroutine内部并没有任何交出控制权的机制，所以它会不停地运行，导致`never_exec_task()`永远无法运行。

新知识get

在我的示例中，publish__XXX是个task没错，应该能交出控制权才对？
图一中的连续执行consumer_worker是否正常？

**Comment by gaogaotiantian** [comment]
``publish_XX``一定不是个task，否则它不会以这种方式出现在call stack上。这就是为什么我问你源代码，没有源代码，你对你代码的理解很可能是有偏差的，我又无从佐证，就很难继续聊。

连续执行consumer_worker当然正常，原因我前面说了，你没有把控制权给出去啊。

**Comment by lijiachang** [comment]
> `publish_XX`一定不是个task，否则它不会以这种方式出现在call stack上。这就是为什么我问你源代码，没有源代码，你对你代码的理解很可能是有偏差的，我又无从佐证，就很难继续聊。
> 
> 连续执行consumer_worker当然正常，原因我前面说了，你没有把控制权给出去啊。

我理解了，感谢您的回复
