### ISSUE TITLE
Pyqt thread detection 

### ISSUE THREAD

**Issue by gedalia** [gaogaotiantian/viztracer#239]
I’m using pyqt to create threads but they don’t seem to be picked up by viztracer. Is there some kind of instrumenting I could do to help?

**Comment by gedalia** [comment]
hi gao

class TestThread(QtCore.QThread):
    """Helper class to build a dict mapping from message index to message timestamp.
    """
    def __init__(self):
        super(TestThread, self).__init__()
        print("TestThread init")


    def run(self):
        print("TestThread run")
        count = 0
        while count < 10: 
            print("background", count)
            count = count + 1
            time.sleep(.5)

print("Main Thread run")
test = TestThread()
test.start()
count = 0
while count < 10: 
    print("main", count)
    count = count + 1
    time.sleep(1)


should be a trivial example that shows it. I had similar issues with the debugger for visual studio code it was necessary to add a call to debug_this_thread() to let it know about the thread
https://github.com/microsoft/debugpy/issues/474
https://github.com/microsoft/debugpy/wiki/API-Reference#debug_this_thread

I wonder if something similar could work. Thanks for looking into it.

**Comment by gaogaotiantian** [comment]
Hi,

Please provide a *complete* demo assuming the person(me) does not know PyQt at all. For example, what is `QtCore`? Also it would be nice to have a formatted code.

Installing Qt also seems to be a non-trivial work. Do you know where's the source code of PyQt? It claims to be open sourced but I did not find the code by some simple search.

**Comment by gaogaotiantian** [comment]
Just to confirm the possible issue, could you try the code below:

```
from viztracer import get_tracer
import sys

# In your threading code(better before most of the stuff)
class YourThread:
    def run(self):
        # This is super hacky, just to confirm whether it works
        sys.setprofile(print(get_tracer()._tracer.threadtracefunc))
```

This should notify the main thread tracer about this thread(even though it should not be used like this)

**Comment by gedalia** [comment]
[thread_test.txt](https://github.com/gaogaotiantian/viztracer/files/8672747/thread_test.txt)
Sorry git trashed the formatting.
I think sudo apt-get install python3-pyqt5 would work there's a list of install commands for various package managers at: https://pythonbasics.org/install-pyqt/
Qt core is just the main qt framework object. qt is known for it's cross platform a widget library, but it's core lib just hides lots of OS dependent code. (sorta like boost or C++ 14/17 does but longer ago) This code creates a QThread object that it then starts up. Not sure if it would be any different than any other os level thread starting up. 
when it runs it looks like this:
Main Thread run
TestThread init
main 0
TestThread run
background 0
background 1
main 1
background 2
background 3
main 2
background 4
background 5
main 3
background 6
background 7
main 4
background 8
background 9
the global interpreter lock stops the prints from stepping on each other.

**Comment by gedalia** [comment]
That appeared to work, Nice
![mt_tracer](https://user-images.githubusercontent.com/264764/167928990-9b3554b0-bed6-447e-9cbb-cd4972422dd1.png)
!

**Comment by gaogaotiantian** [comment]
As of now, you can use this work around to trace threads. This should not have any negative effect, just a bit hacky. I will probably put together a more official way to enable tracing in unusual multi-threading cases. Thanks for the issue, this will expand viztracer to more use cases.

**Comment by gedalia** [comment]
Thanks! I already had to instrument each run-able with that visual studio debug code so it's pretty easy to add that in. Thanks for the quick response, it makes viztracer much more useful for me.

**Comment by gaogaotiantian** [comment]
I made this feature official. You can use it with ``get_tracer().enable_thread_tracing()`` in your thread to get thread trace. It should be released with the latest version soon.
