### ISSUE TITLE
inline profiling multiprocess

### ISSUE THREAD

**Issue by JHu-s** [gaogaotiantian/viztracer#243]
I'm trying to profile the multiprocess (python default one) part of my script only.

By following the documentation, I add the following lines:
```
tracer = VizTracer()
tracer.start()
<call function contains multiprocessing>
tracer.stop()
tracer.save()
```
The result shows main process only.

I did also try the followings:
`viztracer myscript.py`
The result contains both main process and child processes. But the file is too big and can't be loaded with vizviewer.

Is there any way to profile just the multiprocessing part?

**Comment by JHu-s** [comment]
I've also tried log_sparse:
![Screen Shot 2022-06-05 at 2 51 28 pm](https://user-images.githubusercontent.com/63333128/172035863-60e072f6-135f-4a1f-b3df-a087d0937099.png)
![Screen Shot 2022-06-05 at 2 52 12 pm](https://user-images.githubusercontent.com/63333128/172035870-7f46d8d4-93fa-464e-af74-5decccc324bf.png)

How should I interpret the bin plot? It exhibits some gaps, but when clicking on the ForkPoolWorker, it shows the function is executed consecutively without any gaps.

**Comment by gaogaotiantian** [comment]
Inline VizTracer won't work with multiprocessing because there are a lot of monkey patching to do. Only command line `viztracer` will work.

It's true that `vizviewer` is not able to load trace that is too large. The first thing I would suggest is to lower the `tracer_entries` argument. That option is for a single process so when you trace multiple, it will become linearly larger.

There is currently no direct way to disable the trace of the main process. I'll suggest using `max_stack_depth` to limit the stack depth you trace, which will generate a smaller trace file depending on your program.

Overall, VizTracer logs a LOT of information which means if your program is rather complicated, you need to have a basic idea of how your program actually works, and tailor the tracer a bit to trace the most interesting stuff of your program.

`log_sparse` is also something that might of interest if you want to try that.

**Comment by JHu-s** [comment]
Thanks for the quick response!

After setting `max_stack_depth` to 10, the result can be loaded in perfetto. The `tracer_entries` seems a bit tricky. I don't know how it decides which entries to record. I tried different values, and the results only recorded the last two tasks under `mpstar` level  in all cases. 

I did try `log_sparse` to profile just the function that has been pooled. But I suspect this option doesn't log the callstacks? Or there's a way to do it? 

I also have some questions about interpreting the results. What does the bin plot of each process show? I first thought it's cpu usage, but it doesn't align with the execution of functions... And what does the color bar at the top show? 
![Screen Shot 2022-06-05 at 2 51 28 pm](https://user-images.githubusercontent.com/63333128/172041820-11cabcb8-76f1-4967-9d67-bb5a390d41b2.png)
![Screen Shot 2022-06-05 at 2 52 12 pm](https://user-images.githubusercontent.com/63333128/172041863-847a43b9-934f-46fd-8ae4-8997cb8ddc8c.png)

**Comment by gaogaotiantian** [comment]
VizTracer has a circular buffer which would only record the latest entries. Reducing the number of entries will potentially lose the earlier data. You can only have a certain number of entries for vizviewer to display so you'll have to decide which entries those would be (prefer depth or width).

`log_sparse` is designed to log certain functions without callstack, which is mostly used by logging APIs. I could consider adding an extra feature for it to be able to log a certain amount of callstack. That seems reasonable and helpful.

The front-end UI is perfetto, a Google designed trace viewer, and I've customized it a bit. I think the bin of each process is supposed to be the CPU usage and the color might be which process is executing? I never tried to fully understand it, but you can definitely check perfetto's documentation for the details.

**Comment by JHu-s** [comment]
Thanks again for the answers.

Yes, I think it would be helpful if this feature could be added.
I'll check perfetto's documentations for these issues.

**Comment by gaogaotiantian** [comment]
For what it may worth, #244 added support for external trace processor, which means you can deal with large trace logs(In theory, GB-level) now. The change was just merged in and is not officially released. You can try it out by ``pip install git+https://github.com/gaogaotiantian/viztracer`` and then ``vizviewer --use_external_processor``.

**Comment by gaogaotiantian** [comment]
I added the feature to log call stacks with ``@log_sparse`` in #247 . You can now do ``@log_sparse(stack_depth=5)`` to log the descendants of the function. This feature, along with the ``--use_external_processor``, will be released soon.
