### ISSUE TITLE
Write a compressor/decompressor for the trace log file

### ISSUE THREAD

**Issue by gaogaotiantian** [gaogaotiantian/viztracer#249]
Now the trace log file is huge, which is okay on local machines. However, it makes it difficult to share the trace file through network, or to store it somewhere in the cloud.

Most of the info in the trace file is duplicated and we should be able to get a very decent compress ratio for the trace file.

**Comment by Nu1l998** [comment]
I'm trying to write compressor for vizTracer , but i do not know how to start up with a project of c mixed with python . 
maybe , could u tell me a simple way to start a debug env with the "vcompressor" .
in my point , i just need to focus on the impl of the process of compression.

**Comment by gaogaotiantian** [comment]
You can start with `trace-log-compressor` branch, then follow [this](https://github.com/gaogaotiantian/viztracer/blob/master/.github/CONTRIBUTING.md) documentation to setup the environment. You should be able to do `viztracer --compress <your_result.json>` to trigger the existing function.

**Comment by Sefank** [comment]
The example testcase for vcompressor will just fail as the input `vdb_multithread.json` is missing.
I tried to generate this file using `tests/data/vdb_multithread.py` with `--vdb` option and only got a 2.35 KB json, which I would expect larger than exsiting `multithread.json` (105.22KB) as the help of `--vdb` option says that it will bring overhead. 

By the way, it seems that ci is disabled for the new branch `trace-log-compressor` in this repo. Is it intentional?

**Comment by gaogaotiantian** [comment]
`vdb_multithread.json` is checked in and the example test case uses `get_json_file_path("vdb_multithread.json")` to locate it in `test/data` directory. Did you run the test and it failed for you?

``-vdb`` is actually deprecated, but the help message means that it will bring overhead time-wise. You can check the json file and figure out what is not there, FEE or file info.

The CI is disabled on push to any branches other than `master`. However, it is enabled for all the pull requests to any branch.

**Comment by Sefank** [comment]
> `vdb_multithread.json` is checked in and the example test case uses `get_json_file_path("vdb_multithread.json")` to locate it in `test/data` directory. Did you run the test and it failed for you?

I've double checked and confirmed that there is no `vdb_multithread.json` in `tests/data/` which `get_json_file_path` trys to locate.

![files in tests/data/](https://user-images.githubusercontent.com/12670778/187058703-e9658aef-c628-4223-97b9-324f051f6239.png)

**Comment by gaogaotiantian** [comment]
You are correct, this is an error on my side, will fix soon.

**Comment by gaogaotiantian** [comment]
The latest fix is pushed to `trace-log-compressor` branch. There's no need to use `vdb_multithread.json`, it can simply use `multithread.json`. Please pull from the branch to your repo.

**Comment by Milkve** [comment]
Should we consider using protobuf? I think it is good for serializing and de-serializing, and it is popular in RPC cases.

**Comment by gaogaotiantian** [comment]
protobuf is not for compressing. It's an alternative for json.

**Comment by gaogaotiantian** [comment]
The current basic test fails on Windows and I'd love to leave this bug to you guys as a first issue to work on!

**Comment by gaogaotiantian** [comment]
> The document doesn't seems to illustrate the save format of other event, e.g. instant event. Is this determined by me?

I would suggest to make a PR the the protocol first. We can discuss the design, then you can implement it after the design is accepted.

**Comment by LorewalkerZhou** [comment]
For instant event, I consider using the following format:
header(header) - pid(pid) - tid(tid) - name(str) - count(uint64) - [start(ts) - scopes(str)]*

**Comment by LorewalkerZhou** [comment]
> For instant event, I consider using the following format:
> header(header) - pid(pid) - tid(tid) - name(str) - count(uint64) - [start(ts) - scopes(str)]*
header(header) - pid(pid) - tid(tid) - name(str) - scopes(str)-count(uint64) - [start(ts)]* may be a better protocol.

**Comment by LorewalkerZhou** [comment]
> For instant event, I consider using the following format: header(header) - pid(pid) - tid(tid) - name(str) - count(uint64) - [start(ts) - scopes(str)]*

header(header) - pid(pid) - tid(tid) - name(str) - scopes(str)-count(uint64) - [start(ts)]* may be a better protocol.

**Comment by gaogaotiantian** [comment]
> > For instant event, I consider using the following format: header(header) - pid(pid) - tid(tid) - name(str) - count(uint64) - [start(ts) - scopes(str)]*
> 
> header(header) - pid(pid) - tid(tid) - name(str) - scopes(str)-count(uint64) - [start(ts)]* may be a better protocol.

Should probably get a better idea of instant events. For example, `args` is a critical part of an instant event which contains the data that user logs.

**Comment by LorewalkerZhou** [comment]
> Should probably get a better idea of instant events. For example, `args` is a critical part of an instant event which contains the data that user logs.

Since `args` has to be a jsonifiable object, I think we could simpily dump args to string and save it.  

header(header) - pid(pid) - tid(tid) - name(str) - scopes(str)-count(uint64) - [start(ts)-args(str)]*

**Comment by gaogaotiantian** [comment]
> > Should probably get a better idea of instant events. For example, `args` is a critical part of an instant event which contains the data that user logs.
> 
> Since `args` has to be a jsonifiable object, I think we could simpily dump args to string and save it.
> 
> header(header) - pid(pid) - tid(tid) - name(str) - scopes(str)-count(uint64) - [start(ts)-args(str)]*

This is probably doable. You can check in the README first then start prototyping on it.

**Comment by TTianshun** [comment]
Maybe it's a better way to store `arg_name` and `arg_value` separately, for example: 
If a function is called many times and we added '--log_func_args' option. Store the string directly may be redundant because the `arg_name` is stored many times.
