### ISSUE TITLE
vizviewer doesn't exit but hang when OSError: [Errno 48] Address already in use

### ISSUE THREAD

**Issue by pltc325** [gaogaotiantian/viztracer#251]
**Subject of the issue**
vizviewer doesn't exit but hang when OSError: [Errno 48] Address already in use

**Your environment**
macos Mojave 10.14.6

**Steps to reproduce**
1. vizviewer file.json in mac Terminal
2. vizviewer some_other_file.json in Pycharm Terminal

**Expected behaviour**
1. throw OSError: [Errno 48] Address already in use
2. program exits

**Actual behaviour**
1. throw OSError: [Errno 48] Address already in use
2. program hangs

**Comment by gaogaotiantian** [comment]
Thanks for pointing this out. It is fixed in #252 .
