### ISSUE TITLE
vizviewer 修改绑定的端口

### ISSUE THREAD

**Issue by liyuehua-mx** [gaogaotiantian/viztracer#253]
如何修改默认的9001端口？该端口有其他服务

**Comment by gaogaotiantian** [comment]
如果你用的是最新版本的viztracer，理论上在报错的时候应该会直接提示你使用`--port`呀。

**Comment by liyuehua-mx** [comment]
emmm 不清楚😄😄😄可能当时我没有仔细看报错吧，感谢，viztracer帮了我大忙
