### ISSUE TITLE
multiprocessing tree - missing traces for lower level processes

### ISSUE THREAD

**Issue by danielhrisca** [gaogaotiantian/viztracer#260]
Hello,

I'm trying to profile a multiprocessing application that has a tree-like process structure:

- main process running a PySide6 GUI
    - secondary process started from the main process
         - after some user configuration the secondary process starts several child processes

The issue is that the final report contains only the tracing for the main and secondary processes. 

I'm running viztracer with this command ``viztracer -o result.html .\myapp.py``

**Comment by gaogaotiantian** [comment]
The multiprocessing does not happen magically, it relies on some hook trick on the `multiprocessing` library. I'm not familiar with PySide6 GUI, and I don't know how your secondary process spawns its child processes. However, from the command you gave, I suspect you are working on Windows? If you are using `multiprocessing` library on Windows, the instrumentation will not be installed on processes spawned, so the child processes of spawned process will not be logged.

Processes from `os.fork()`, `multiprocessing` with fork(Linux) and `subprocess` should work.

However, I believe that there's a solution to this problem, I'll work on it recently.

**Comment by danielhrisca** [comment]
Yes,  the application runs on windows and the processes are created using the multiprocessing module,  not the Qt facilities

**Comment by gaogaotiantian** [comment]
I checked in the feature for supporting multi-process from sub-process so any depth of nested multi-process should in theory work. You can try it out by `pip install git+https://github.com/gaogaotiantian/viztracer`. This feature will be released in next release.
