### ISSUE TITLE
Make vizviewer test more stable on Mac on github actions

### ISSUE THREAD

**Issue by gaogaotiantian** [gaogaotiantian/viztracer#269]
Now vizviewer test sometimes fails on nightly validations([example](https://github.com/gaogaotiantian/viztracer/runs/8056885257?check_suite_focus=true)). It's not a real failure, just the port is somehow occupied. As vizviewer does support custom ports, we can maybe check if the port works first, then try to test on it, which will reduce the fake positives in nightly validation.

**Comment by acehinnnqru** [comment]
So can I just try another port?

**Comment by gaogaotiantian** [comment]
Well, not exactly. We should *not* simply try different ports after failing on a port, as there might be some cavets like "it will always fail on the first try". We should use another independent way to confirm a port is working, before we try `vizviewer` on that port.

**Comment by acehinnnqru** [comment]
I see. Could we provide a method to find a free port that is not working and then try to test `Viewer` on it?

**Comment by gaogaotiantian** [comment]
Yes, we can implement a new method in the test class to find a free port first, then test on it.

**Comment by acehinnnqru** [comment]
If we find a free port first, the cases to test `use_external_processor` option can use this port but not 10000. Right?

**Comment by acehinnnqru** [comment]
I melt a problem when I complete my codes: The test_use_external_processor case could not pass. And when I try to execute `vizviewer --use_external_processor temp.json`, it took a long time but nothing happened until I killed it. I don't know what happened.
My device is Macbook Pro M1 Max. I can see the Python took a 100% CPU usage like it melt a dead loop.

**Comment by gaogaotiantian** [comment]
> If we find a free port first, the cases to test `use_external_processor` option can use this port but not 10000. Right?

No, `test_use_external_processor` is another thing. The issue is about the other general tests which usually run on port 9001. You can refer to the example link for a failure case.

**Comment by acehinnnqru** [comment]
> > If we find a free port first, the cases to test `use_external_processor` option can use this port but not 10000. Right?
> 
> No, `test_use_external_processor` is another thing. The issue is about the other general tests which usually run on port 9001. You can refer to the example link for a failure case.

Oh, I see.

**Comment by gaogaotiantian** [comment]
This issue is fixed by #286.
