### ISSUE TITLE
asyncio support?

### ISSUE THREAD

**Issue by Ehco1996** [gaogaotiantian/viztracer#28]
add one `tracer` object when loop start and call  tracer.stop(),trace.save() when loop stopped

but the generated html don't show any traces but one `loop.run_forever`

is anything wrong ?
<img width="1678" alt="截屏2020-10-26 下午2 00 42" src="https://user-images.githubusercontent.com/24697284/97139019-7cb88c00-1794-11eb-8595-16263e3f4180.png">

**Comment by gaogaotiantian** [comment]
All those "lines" are traces. Use "AWSD" to navigate and zoom in.

**Comment by Ehco1996** [comment]
@gaogaotiantian thanks~
