### ISSUE TITLE
Could Viztracer record the consuming time of GPU computation?

### ISSUE THREAD

**Issue by erjiaxiao** [gaogaotiantian/viztracer#283]
Hello Tian! Since GPU computation is nonsynchronous in machine learning, in this situation, could viztracer trace the consuming time of GPU?

**Comment by gaogaotiantian** [comment]
viztracer can only trace functions on python level, including C calls from python, without any extra instrumentation. There's not existing mechanism to log any resource comsumption accurately, including memory and CPU, so I don't think viztracer can trace the consumption of GPU.

**Comment by erjiaxiao** [comment]
@gaogaotiantian I see. So you mean if we utilize python as an interface to do calculation on GPU and syncronize until the calculation is done, then the whole time consumption will be recorded by Viztracer, although we cannot see the exact time consumption on GPU?

**Comment by gaogaotiantian** [comment]
That's correct. There's no way to hook to GPU usage implicitly. If you have an explicit call to invoke GPU and you have control over it, you can probably add an explicit hook there to log an event, but that's another topic.

**Comment by erjiaxiao** [comment]
@gaogaotiantian Thank you! It really helps a lot!
