### ISSUE TITLE
Thread names with quotes and newlines cause JSON decode errors in report_builder.py:get_json

### ISSUE THREAD

**Issue by jtkouz** [gaogaotiantian/viztracer#285]
Some of my threads are named with a file name and have newlines, e.g.,
`{"ph":"M","pid":23061,"tid":23060,"name":"thread_name","args":{"name":"  File "./something/otherthing.py", line 123, in exec_func_slaves
    pool = concurrency.ThreadPool(max_workers=min(num_workers, concurrency.THREAD_POOL_SIZE_MEDIUM))
_0"}}`

I worked around this by fixing up the json_str at
report_builder.py:29 for my particular data.

**Comment by gaogaotiantian** [comment]
We should probably come up with a way to escape the non json compatible characters.

**Comment by gaogaotiantian** [comment]
The fix is released with 0.15.5
