### ISSUE TITLE
使用viztracer --log_func_args -m locust 程序无法ctrl+c退出

### ISSUE THREAD

**Issue by xpf629629** [gaogaotiantian/viztracer#291]
```bash
# 使用方式
viztracer --log_func_args -m locust  # locust是一个开源库
```
我还需要提供其他信息吗？
我该如何让程序退出，并且获得追踪报告？

**Comment by gaogaotiantian** [comment]
你使用的OS，viztracer和python版本？

**Comment by xpf629629** [comment]
os win10
viztracer 0.15.4
python 3.9.13
不加 log_func_args参数是可以的

**Comment by xpf629629** [comment]
```
# 这样使用，ctrl+c能正常退出
python -m locust
# 这样使用，ctrl+c能正常退出
viztracer -m locust
```

**Comment by gaogaotiantian** [comment]
我尝试了一下，我怀疑是因为`--log_func_args`增加了很多的overhead导致你的程序在import阶段耗费了太多时间，然后让你以为它卡住了。在我的电脑上，这个阶段用了大概25秒。

你可以看一下，当你使用`--log_func_args`的时候，有没有出现`Starting web interface at http://0.0.0.0:8089`。如果没有，说明这个server还没有跑起来，这时候Ctrl+C有可能会有问题。你可以等它出来之后（也就是server跑起来了）再试一下。我是可以正常的Ctrl+C退出的。

如果你不想等，你可以试着加一下`--ignore_frozen`，它会忽略所有的import的内容，应该就可以直接把你的server跑起来了。如果你不是很在意import的部分，这也是个非常好的选择。

**Comment by xpf629629** [comment]
```
(python39_env) PS C:\Users\xuxx\Desktop\新建文件夹> viztracer --log_func_args --ignore_frozen -m locust 
# 2秒左右出现这两行记录 ， 如果不加ignore_frozen 5秒左右
[2022-10-19 09:19:39,928] DESKTOP-AP4HM1O/INFO/locust.main: Starting web interface at http://0.0.0.0:8089 (accepting connections from all network interfaces)
[2022-10-19 09:19:40,096] DESKTOP-AP4HM1O/INFO/locust.main: Starting Locust 2.12.2
```
我每次使用ctrl+c时 都是控制台输出`Starting Locust 2.12.2`之后， 并且我还尝试过在server跑起来之后等更长的时间（10来分钟）

在server跑起来之后，如果我频繁ctrl+c,  程序会在不确定多少次 ctrl+c 时退出，并在控制台输出
```
# 截取的部分输出
KeyboardInterrupt
[2022-10-19 09:43:49,721] DESKTOP-AP4HM1O/INFO/locust.main: Shutting down (exit code 0)
# 还有一条这个记录
Saving trace data, this could take a while
```
因为频繁ctrl+c ，我可能终止了`saving trace data`，导致只有`Saving trace data, this could take a while`输出

**Comment by xpf629629** [comment]
我装了虚拟ubuntu，在ubuntu中`viztracer --log_func_args` -m locust 是工作的

**Comment by gaogaotiantian** [comment]
我可以在windows上复现这个问题，目前来看有一些比较深层的问题，我需要一些时间来搞清楚然后解决它。

**Comment by gaogaotiantian** [comment]
我研究了一下这个问题，我的结论是，目前这个阶段，这件事大概率是无解的。

尽管viztracer现在确实有一些地方处理的是有毛病的，但是这个问题最大的根源是gevent（也就是locust基于的异步方案）的错误处理方式。它用的错误处理方式很怪，它需要在exception的traceback里有一个专门的定位loop的variable。在正常的python代码运行里，这是没啥问题的，但是如果你的exception是在一个比较奇怪的地方发生的（函数刚开始），就可能会导致没有traceback，然后它的退出机制就乱套了。

这件事只在windows上能复现，应该是因为windows对Ctrl+C的机制的处理和Linux是不同的。而只在``--log_func_args``下会复现，是因为``--log_func_args``这个事情太耗费时间了，导致你的Ctrl+C大概率是interrupt在logging里的。

也就是说，即便我修复了现在viztracer的一些在处理exception上的毛病，也没办法让``--log_func_args``正常工作。当然也有可能是我对gevent的理解还不够透彻……或许有个gevent的专家愿意研究这个问题可能可以得到比我更有用的结论。

目前来看，我暂时只能把这个问题label成won't fix了。

**Comment by xpf629629** [comment]
感谢您及时的回复！viztracer 是非常棒的工具
