### ISSUE TITLE
chore: replace `self.assertTrue(os.path.exists(f))` with `self.assertFileExists(f)`

### ISSUE THREAD

**Issue by tanloong** [gaogaotiantian/viztracer#302]
I believe this [change](https://github.com/gaogaotiantian/viztracer/compare/master...tanloong:viztracer:use-assertFileExists) is useful, as `self.assertFileExists` will give more detailed `err_msg` if a corresponding test fails.

May I create a PR?

**Comment by gaogaotiantian** [comment]
Sure, this gives a bit more information about the path, even though I'm not sure if that would be useful for investigation, but it's definitely not worse. Also the code is cleaner.
