### ISSUE TITLE
multiprocessing profiling does not work with inline viztracer

### ISSUE THREAD

**Issue by speakless86** [gaogaotiantian/viztracer#306]
version 0.15.6
python 3.8.10

I am trying to integrate viztracer with bazel but run into the following blocking issue that inline viztracer can not generate profiling reports for subprocess.

It works well via command line:
```
from multiprocessing import Pool
import os
import time

from viztracer import VizTracer, get_tracer


def init_worker():
    """Init worker to print pid."""
    pid = os.getpid()
    print(f'pid={pid}')


def main():

    # pylint: disable=unused-variable
    def afterfork_callback(tracer):
        print('afterfork_callback')

    get_tracer().set_afterfork(afterfork_callback)
    with Pool(5, initializer=init_worker) as pool:
        pool.map(time.sleep, [5] * 5)


if __name__ == "__main__":
    main()
```
Running results:
```
$ viztracer test.py 
afterfork_callback
pid=2169334
afterfork_callback
pid=2169335
afterfork_callback
pid=2169336
afterfork_callback
pid=2169337
afterfork_callback
pid=2169338
Total Entries: 4280                                                             
Use the following command to open the report:                                                         
```
![Screen Shot 2022-12-29 at 1 09 46 PM](https://user-images.githubusercontent.com/4011378/210011399-d1c72b36-6a95-4b37-9f4b-2e8711122e9b.png)

But all subprocess profiling info will disappear if we switch to use with inline code:
```
from multiprocessing import Pool
import os
import time

from viztracer import VizTracer


def init_worker():
    """Init worker to print pid."""
    pid = os.getpid()
    print(f'pid={pid}')


def main():

    # pylint: disable=unused-variable
    def afterfork_callback(tracer):
        print('afterfork_callback')

    with VizTracer() as tracer:
        tracer.set_afterfork(afterfork_callback)
        with Pool(5, initializer=init_worker) as pool:
            pool.map(time.sleep, [5] * 5)
```
Running results:
```
$ python3 test.py 
pid=2169028
pid=2169029
pid=2169030
pid=2169031
pid=2169032
Loading finish                                        
Total Entries: 3673                                                             
Use the following command to open the report:
```
Note that the total entries are much less and also there is no log printed in `afterfork_callback`.

![Screen Shot 2022-12-29 at 1 06 00 PM](https://user-images.githubusercontent.com/4011378/210011096-763778b8-507c-49ed-bc65-ef4034f601ab.png)

Is it a bug?

**Comment by gaogaotiantian** [comment]
Unfortunately, making multiprocessing work is not trivial. So yes, inline VizTracer does not support multiprocessing because there are a couple of things that need to be done to make it work and I have not figured out a way to do it. It's not a bug, it's expected.

You may be able to hack some prototype from the code in [main.py](https://github.com/gaogaotiantian/viztracer/blob/master/src/viztracer/main.py), but it's definitely more than a few lines.
