### ISSUE TITLE
Doesn't seem to track doubly nested multiprocessing.Processes

### ISSUE THREAD

**Issue by zplizzi** [gaogaotiantian/viztracer#310]
I'm finding that viztracer doesn't seem to trace sub-sub-processes, when both levels of processes are `multiprocessing.Process`es. Subprocesses work fine but they seem to get lost on the second level of nesting. It's possible this is something specific to my setup though.

**Comment by gaogaotiantian** [comment]
Which version of VizTracer are you using? I believe this should be fixed in #264 which means it should be working since 0.15.4.

**Comment by zplizzi** [comment]
This is with `0.15.6` unfortunately.

**Comment by zplizzi** [comment]
Actually, I could swear I saw this earlier, but when I go to reproduce it now, everything seems to be working fine. I'll reopen this if I see it again. It's possible I was just interpreting things wrong.

**Comment by gaogaotiantian** [comment]
Please let me know if you could reproduce it. It's possible there's something wrong with my patch. Making multiprocessing work out of the box is not trivial :)
