### ISSUE TITLE
Error: RPC framing error

### ISSUE THREAD

**Issue by ManishwarG** [gaogaotiantian/viztracer#317]
I tried to viztracer it has successfully generated .json file but I am unable to view it, any help is appritiated.
PS: I am new to profiling.
![image](https://user-images.githubusercontent.com/105509376/222722768-086ac072-31fc-4c10-9ab1-78cd306324b5.png)

**Comment by gaogaotiantian** [comment]
This is probably a dupilicate of #139 and #237.

The short version is - this is a FireFox issue, switch to Chrome.

If Chrome still does not work, please reopen this issue. I'm also happy to discuss this issue with you in this thread if you are interested. But for now, I'll close the issue.
