### ISSUE TITLE
NameError: name 'false' is not defined. Did you mean: 'False'?

### ISSUE THREAD

**Issue by et2300** [gaogaotiantian/viztracer#320]
in termux proot (in android run linux) 
NameError: name 'false' is not defined. Did you mean: 'False'?
???

**Comment by gaogaotiantian** [comment]
Could you provide a repro instruction? What code did you trace? What's the command you used to trace it? What's the full error? Most importantly, is this related to viztracer?

**Comment by et2300** [comment]
@go
![Uploading Screenshot_20230328-162507.png…]()

**Comment by et2300** [comment]
![Screenshot_20230328-162418](https://user-images.githubusercontent.com/81605900/228176428-66901d45-7c76-455d-98c5-f4915e296a03.png)

**Comment by et2300** [comment]
![Screenshot_2023-03-28-16-20-48](https://user-images.githubusercontent.com/81605900/228176695-8b5aa738-fa0a-4702-990c-e95d9c8a2cbc.jpg)

**Comment by et2300** [comment]
`from typing import Set
import operator as op

variables = {}


class MyCode:
    index = 0

    def __hash__(self):
        MyCode.index += 1
        return MyCode.index

    def do(self):
        ...


class SetValue(MyCode):
    """赋值 a = 15 语句"""

    def __init__(self, name, value):
        self.name = name
        self.value = value

    def do(self):
        variables[self.name] = self.value

    def __str__(self):
        return "<SetValue>"


class GetValue(MyCode):
    def __init__(self, name):
        self.name = name

    def do(self):
        return variables[self.name]


class ChangeValue(MyCode):
    # i += 1
    def __init__(self, name, dv, op):
        self.name = name
        self.dv = dv
        self.op = op

    def do(self):
        variables[self.name] = self.op(variables[self.name], self.dv)


class Op(MyCode):
    # i < 1000
    def __init__(self, left, operator, value):
        self.left = left
        self.operator = operator
        self.value = value

    def do(self):
        if isinstance(self.left, str):
            return self.operator(variables[self.left], self.value)
        elif isinstance(self.left, MyCode):
            return self.operator(self.left.do(), self.value)
        else:
            return self.operator(self.left, self.value)


# class Judge(MyCode):
#     def __init__(self, name, value):
#         self.name = name
#         self.value = value
#
#     def do(self):
#         return variables[self.name] == self.value
#
#     def __str__(self):
#         return "<Judge>"


class If(MyCode):
    def __init__(self, *args, **kwargs):
        if len(args) == 4:  # if ((condition) {} else {})
            # if (() {})
            self.condition = args[0]
            self.doCode: Set[MyCode] = args[1]
            self.elseDo: Set[MyCode] = args[3]
        elif len(args) == 2:
            self.condition = args[0]
            self.doCode: Set[MyCode] = args[1]
            self.elseDo: Set[MyCode] = set()

    def do(self):
        if self.condition.do():
            for code in self.doCode:
                code.do()  # bug
        elif self.elseDo:
            for code in self.elseDo:
                code.do()

    def __str__(self):
        return "<IF>"


class For(MyCode):
    def __init__(self, initContent, judgeContent, loopContent, loopCode):
        self.initContent = initContent
        self.judgeContent = judgeContent
        self.loopContent = loopContent
        self.loopCode: Set[MyCode] = loopCode

    def do(self):
        self.initContent.do()
        while self.judgeContent.do():
            for code in self.loopCode:
                code.do()
            self.loopContent.do()


class Print(MyCode):
    def __init__(self, string):
        self.string = string

    def do(self):
        if isinstance(self.string, str):
            print(self.string)
        elif isinstance(self.string, MyCode):
            print(self.string.do())


class NameSpace:
    def __init__(self, *args):
        self.arr = args

    def run(self):
        for code in self.arr:
            code.do()


# 打印出0~1000内左右的偶数

# 打印出0~1000内左右的偶数
ns = NameSpace(
  For({}{}

def main():
    ns.run()
    # print(variables)


if __name__ == "__main__":
    main()
`

**Comment by et2300** [comment]
![Screenshot_20230328-163324](https://user-images.githubusercontent.com/81605900/228178219-977d7736-f2d6-4fab-9f27-999f9ae5b282.png)

**Comment by et2300** [comment]
do you can use ssh to console ?
ipv6 address 240e:0325:5641:8a00:4137:fa97:86dc:c4ce
username u0_a330 
password "password"

**Comment by gaogaotiantian** [comment]
@TTianshun was right - you need to use vizviewer to open your report, not viztracer.
