### ISSUE TITLE
远程使用问题

### ISSUE THREAD

**Issue by yofufufufu** [gaogaotiantian/viztracer#322]
我在远程服务器上获取到result.json文件，由于远程服务器使用图形界面不方便，我将结果下载到PC后用perfetto打开，出现如下错误：
> To assist with debugging please attach or link to the trace you were viewing.
Viewed on: https://ui.perfetto.dev
Failure parsing JSON: encountered fatal error while parsing key
"Failure parsing JSON: encountered fatal error while parsing key"
v32.1-1f0f1aa6b 1f0f1aa6babb0b3ff273c5102aa677b2604e9a4e
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36

我也尝试了端口转发，将服务器的9001端口转发到PC的19001端口上，但是访问127.0.0.1:19001时出现错误：
![image](https://user-images.githubusercontent.com/52293720/229469280-a4c2cc07-5435-46dd-a66b-2b19a566dd83.png)

**Comment by gaogaotiantian** [comment]
你的这个json文件多大？你说的用“perfetto”打开是用的官方的perfetto还是vizviewer？浏览器用的什么？

**Comment by yofufufufu** [comment]
> 你的这个json文件多大？你说的用“perfetto”打开是用的官方的perfetto还是vizviewer？浏览器用的什么？

您好，json文件大小164MB，我说的perfetto指的是官方的：https://ui.perfetto.dev/ 
PC上的浏览器是Google

**Comment by gaogaotiantian** [comment]
你尝试过在本地安装一下viztracer然后用vizviewer打开这个json么？
