### ISSUE TITLE
[Minor Suggestion] vizviewer's CLI parameter is best assigned double quoted path. E.g. `$ vizviewer "/path/to my google drive/my code/result.json"` 

### ISSUE THREAD

**Issue by davidleejy** [gaogaotiantian/viztracer#324]
Hi, just writing in to contribute a minor point. If the path to the viztracer result's json file contains spaces, then double quotes need to be applied around the path before assigning it as a CLI argument to viztracer. 

Sometimes, users work with paths that contain spaces by default; Google drive paths appears to contain spaces by default like: `/Users/d/Library/CloudStorage/GoogleDrive-xxx@yyy.com/My Drive/code/viztracer-result.json`.

So:

```bash
$viztracer "/path/to my google drive/my code/result.json"
```

will work. 

However, leaving out the double quotes won't work.

While running, Viztracer prints to stdout something like:

```bash
Use the following command to open the report:
vizviewer /path/to my google drive/my code/result.json
```

This command, when copied and applied directly, doesn't work. It might be a good idea to just add double quotes around that so that it reads:

```bash
Use the following command to open the report:
vizviewer "/path/to my google drive/my code/result.json"
```

Minor point, but I hope it helps 🙂

**Comment by gaogaotiantian** [comment]
This sounds reasonable. I'll add it soon.
