### ISSUE TITLE
Reason for large gaps?

### ISSUE THREAD

**Issue by arbenede** [gaogaotiantian/viztracer#335]
I see some long gaps (> 1 s) in a function that I am tracing. Is there any way to figure what is python doing during these? Maybe the garbage collector is doing something?

![image](https://user-images.githubusercontent.com/3598071/234970903-9f3154f0-6eab-4b9a-b7cd-81a704feaf1e.png)

**Comment by gaogaotiantian** [comment]
You should be able to see the function this gap is in. Unfortunately your screenshot does not show it. I don't think gc could take 1s. You need to compare the result with source code. If you have your source code somewhere and a better displayed trace file, I can take a quick look.

**Comment by arbenede** [comment]
Tian, thanks for your prompt reply. I know the function that the gaps are in. I'm wondering what are the lines of code that are taking so long. Maybe I should just encapsulate all the code in that function inside extra functions so that viztracer can trace them and report the times? The majority of the code in that function are just calls to scipy functions.

**Comment by gaogaotiantian** [comment]
So, calling to scipy functions should be recorded properly. VizTracer is able to trace all "calls". However, if it's just bytecode executing without any function call, VizTracer won't be able to detect that.

You can put your code in a separate function to "trigger" VizTracer, but there's a simpler way without moving your code too much, you can do a manual [event](https://viztracer.readthedocs.io/en/latest/custom_event_intro.html?highlight=event#duration-event):

```python
from viztracer import get_tracer

with get_tracer().log_event("my event name"):
    # some code running here
```

It will appear as a call to the code inside in VizTracer, and you only need a batch indent for the code you want to trace. Let me know if you have more questions.

**Comment by arbenede** [comment]
Yes, this worked very well. Thanks again, I'm closing the issue.
