### ISSUE TITLE
Event missing in multiprocess application

### ISSUE THREAD

**Issue by manuelporta** [gaogaotiantian/viztracer#337]
Hi! I'm trying to debug an issue inside my code using viztracer.
I When looking at the results with vizviewer there is a missing function in one process.
![imagen](https://github.com/gaogaotiantian/viztracer/assets/11397945/59754bed-6df6-497a-88b9-8a65a3f39684)
In this screenshot it can be seen that, inside start(), the program calls connect() and then read() but connect does not appear under read or in any other place in the logs.

I obtained the logs using "viztracer main.py"
I have also tried focusing on the "connect()" function with the @log_sparse decorater and the --log_sparse funcion, but the funcion was still missing.
Finally, I tried to log some custom events adding "# !viztracer: log_instant("Start connect")" inside connect() and "--magic_comment" at the command line, but they were also missing in the logs.

Any idea of why this is happening?

**Comment by gaogaotiantian** [comment]
I believe it's because your data overflowed. There should be a warning in your command line output saying that there will be data missing.

**Comment by manuelporta** [comment]
Thank you so much for your answer! I 'hand't seen the warning.
I edited the number of entries with --tracer_entries and now everything is on its place.
Thank you again for your amazing job!
