### ISSUE TITLE
can not trace when a file contains os._exit()

### ISSUE THREAD

**Issue by yihong0618** [gaogaotiantian/viztracer#340]
viztracer mypy # this work

viztracer mypy some.py # this not work

Minimize the reproduction of this program
cat a.py
```py
import os

def a():
    return 2

def b():
    return 3

def c():
    return a() + b()

c()
os._exit(0)
```
viztracer a.py # this generate nothing

**Comment by gaogaotiantian** [comment]
This is not a bug. os._exit() terminates the process brutally so no exit hook has a chance to execute. You’ll experience the same issue with any library that requires an exit hook using this code, for example, coverage.

**Comment by yihong0618** [comment]
Make sense and really thanks for your great tool.
