### ISSUE TITLE
possible to flush tracing periodically ?

### ISSUE THREAD

**Issue by comicfans** [gaogaotiantian/viztracer#341]
Hello, I found some Python package signal handling will break python [for example this](https://stackoverflow.com/questions/15457786/ctrl-c-crashes-python-after-importing-scipy-stats)
and [this](https://docs.python.org/3/library/asyncio-eventloop.html#set-signal-handlers-for-sigint-and-sigterm)

pressing ctrl-c just terminates whole python, leave viztracer no chance to dump tracing, I wonder if viztracer can periodically flush tracing to disk, or have some external control method (say, handle a SIGUSR or check some special filepath periodically) to immediately dumping all trace ?

**Comment by gaogaotiantian** [comment]
As long as you don't crash Python or use `os._exit()`, `viztracer` should have a chance to dump trace. Even if you hooked `SIGINT` or `SIGTERM`.

Periodically dumping trace is a huge performance impact and should only be done explicitly by users. `SIGUSR` is only available on Linux and is already used for legacy attaching. If you have control over the code, it's easy to do - just write a small piece of code to save the trace with any trigger you like.

Is there a real usage or this is hypothetical?

**Comment by comicfans** [comment]
question is that with some package running, ctrl-c do crash whole python even without viztracer.

it's a long-running process, with async logic, run for a day, and ctrl-c doesn't give any backtrace, thus I need some tracing method to inspect what's happening (near realtime).  my first try is to insert some logging and convert them to chrome trace, but that's not scalable. 

then I found viztracer may resolve my problem, run it as 
```
python -m viztracer my_script
```
after some running time,   ctrl-c still crashes everything and nothing saved. I can confirm viztracer do dumping trace before my script ctrl-c at early time ( but during that time my script won't crash by ctrl-c so I can already inspect backtrace, thus viztracer doesn't help)


trigger dump in my code maybe also possible, but I have some question for it:

1. is it possible to call viztracer dump if I run script by python -m viztracer ?
2. if 1 is impossible, is viztracer dump function thread safe, so I can call it from other thread ? because of possible hang problem, main thread may be blocked so call dump from main thread is not ideal


I didn't view the logic of viztracer and am not sure if this is reasonable, maybe viztracer can stream tracing output (maybe just intermediate format, user can convert it to final trace format offline), this has some advantages:

1. don't need to keep all the trace, save memory
2. can view the program process continuously, instead of waiting for the whole program to finish.  
3. chrome tracing will show 'unfinished' block if tracing don't have corresponding E mark, so it help debugging hang problem (since we can view it during process still running , it can quickly find the hang point)

**Comment by gaogaotiantian** [comment]
People have different definitions for "crashing" - if your program exit with a C-level error(SegFault), that should be reported to CPython. If it exits with an exception, that could be handled by viztracer (and not a CPython defined crash).

I can help with the viztracer related question though:

1. Yes, it's possible to dump data even if you run your script with the command line tool. In your code, just do:

```python
from viztracer import get_tracer

def save():
    tracer = get_tracer()
    tracer.save()

def your_function():
    ...
    # Dump the data
    save()
```

2. `save()` should be thread-safe because it will turn off the collecting first. There's also a forked version - `fork_save()` - that would fork first then do the saving.

Not streaming the output is a design choice - for performance. Users are using viztracer for profiling a lot, so performance is critical. Writing to disk cost too much time to do.

**Comment by comicfans** [comment]
ok I'll take a try, Thank you for this. and is fork_save work under windows ?

**Comment by gaogaotiantian** [comment]
It should work - not a lot of users actually use that feature even though it's been tested.
