### ISSUE TITLE
Please verify that the --pid_suffix option works as intended

### ISSUE THREAD

**Issue by gaogaotiantian** [gaogaotiantian/viztracer#346]
### Discussed in https://github.com/gaogaotiantian/viztracer/discussions/345

<div type='discussions-op-text'>

<sup>Originally posted by **kllp** June 13, 2023</sup>
Recent versions of viztracer don't seem to append the PID to the filename. Instead it creates `result.json`.

`viztracer --pid_suffix single_process.py` appends the PID in version 0.12.3 but not in 0.15.6

https://viztracer.readthedocs.io/en/latest/concurrency.html#combine-reports</div>

**Comment by TTianshun** [comment]
Seemed that `ofile` with `pid_suffix` is not set correctly in `VizUI`. I can make a pr to fix it.
