### ISSUE TITLE
Failed when launching vizviewer

### ISSUE THREAD

**Issue by LaoshuBaby** [gaogaotiantian/viztracer#352]
During the process of starting vizviewer, the following error was given:

```
Trace: http://127.0.0.1:9001/localtrace

Viewed on: http://127.0.0.1:9001

Error: RPC framing error
onRpcResponseMessage@http://127.0.0.1:9001/v25.0-cca3e0ce7/frontend_bundle.js:82366:19
onRpcResponseBytes@http://127.0.0.1:9001/v25.0-cca3e0ce7/frontend_bundle.js:82326:18
onMessage@http://127.0.0.1:9001/v25.0-cca3e0ce7/frontend_bundle.js:82656:15


v25.0-cca3e0ce7 cca3e0ce7300e9ab1616888edfd92238fbc27378
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/114.0
```
like that: (I don't have a google account, so I create an issue here)
<img src="https://github.com/gaogaotiantian/viztracer/assets/42690037/602b28ed-5a2b-4f3e-a1da-5789262544e6" width=250px/>

But there is no error message in my terminal:
```
PS E:\Data\OSM> vizviewer E:\Data\OSM\result.json
Running vizviewer
You can also view your trace on http://localhost:9001
Press Ctrl+C to quit
```
When I used vizviewer for the first time, the Windows firewall asked me, and I allowed it.
The html file I generated using vietracer filename.py -o result.html can be opened normally.
I install viztracer with command `pip install viztracer[full]`, and using python 3.11.2. Viztracer's version is 0.15.6

The `result.json` maybe a little big? It's 106MB large, perhaps because it's was used to read a 300MB+ dataset?

**Comment by gaogaotiantian** [comment]
It is a known and unfixable issue that Firefox does not work well with large trace log. Please use Chrome.

html report is basically deprecated (at least not maintained) at this point.

Could you try Chrome and see if it works?

**Comment by LaoshuBaby** [comment]
> Could you try Chrome and see if it works?

Yes, it works well on Chrome, thank you!
I didn't try to use "Firefox" as the keyword when I searched for similar issue before, it is a duplicate of #208, #237 and #317, so I am very sorry that I created a duplicate issue.

I noticed that we currently haven't a feature that can specify to use Chrome while open "http://127.0.0.1:9001/", I've thought about webbrowser and selenium, but neither looks like a good solution：

webbrowser need a given chrome path, and this can vary greatly depending on the operating system. selenium is too heavy for just open a browser (chromedriver is also needed to be installed). Do you have any suggestions about open with Chrome?

**Comment by gaogaotiantian** [comment]
Not really. Currently vizviewer uses `webbrowser` to open trace logs. Firefox works for smaller trace files, but I don't know any good way to prioritize Chrome.
