### ISSUE TITLE
⭐️support pathos.multiprocessing

### ISSUE THREAD

**Issue by zhengow** [gaogaotiantian/viztracer#355]
Cuz multiprocessing can't support some args unpicklable, so we need pathos

**Comment by gaogaotiantian** [comment]
I don't think pathos is popular enough for viztracer to add custom support. It's not that complicated to support it, but the code is kind of ugly. pathos basically forked a version of multiprocessing and renamed it to multiprocess. At this point, I don't think viztracer will add extra code for it.
