### ISSUE TITLE
Image link mistake of README doc

### ISSUE THREAD

**Issue by zhaojames0707** [gaogaotiantian/viztracer#36]
The image of **Multi Thread Support** is https://github.com/gaogaotiantian/viztracer/blob/master/img/multithread_example.png, but the click link is https://github.com/gaogaotiantian/viztracer/blob/master/img/example.png.

**Comment by gaogaotiantian** [comment]
Thanks, fixed in https://github.com/gaogaotiantian/viztracer/commit/efeaf9bdae654040cd9a830f61c13ae75f6340a2
