### ISSUE TITLE
`SNAPTRACE_TRACE_SELF` typo at `snaptrace.c`

### ISSUE THREAD

**Issue by AlexeyKozhevin** [gaogaotiantian/viztracer#363]
https://github.com/gaogaotiantian/viztracer/blob/cb8934f55644e562a7fa3b8371cf427b91a68a34/src/viztracer/modules/snaptrace.c#L1251

Potentially, it's a typo: the second check is for `kw_log_async` instead of `kw_trace_self`.

**Comment by gaogaotiantian** [comment]
This is true, do you want to just fix it with a PR? I can do it if you feel this is too trivial.

**Comment by AlexeyKozhevin** [comment]
Yes, I'll do
