### ISSUE TITLE
vizviewer fails

### ISSUE THREAD

**Issue by diekhans** [gaogaotiantian/viztracer#365]
`vizviewer result.json `

using https://hgwdev.gi.ucsc.edu/~markd/bug-reports/viztracer/result.json.gz

results in

```
Oops, something went wrong. Please file a bug.
race: http://127.0.0.1:9001/localtrace

Viewed on: http://127.0.0.1:9001

Error: RPC framing error
onRpcResponseMessage@http://127.0.0.1:9001/v25.0-cca3e0ce7/frontend_bundle.js:82366:19
onRpcResponseBytes@http://127.0.0.1:9001/v25.0-cca3e0ce7/frontend_bundle.js:82326:18
onMessage@http://127.0.0.1:9001/v25.0-cca3e0ce7/frontend_bundle.js:82656:15


v25.0-cca3e0ce7 cca3e0ce7300e9ab1616888edfd92238fbc27378
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/116.0

```

**Comment by diekhans** [comment]
If I use chrome, rather than firefox, this error doesn't occur

**Comment by gaogaotiantian** [comment]
This is a known issue #139 . Search Firefox in issues and you’ll find multiple dups. This is a limitation for Firefox running perfetto and viztracer  has no control over it. The solution is simply to use chrome. Close as dup.
