### ISSUE TITLE
Bug: args that overlap with viztracer is lost in subprocess.Popen

### ISSUE THREAD

**Issue by RmZeta2718** [gaogaotiantian/viztracer#378]
**Describe the bug**

Any command line argument that belongs to `viztracer` (`--output_dir` for example) will be lost when user program calls `subprocess.Popen`.

I found this bug when using deepspeed launcher. After a short investigation, I found the key is `Popen` in the launcher. So I made a minimum script to reproduce.

**Steps to reproduce**

`launcher.py` is the program to run by `viztracer`, `launcher` itself calls another program by `Popen`:

```python
import argparse
import subprocess

parser = argparse.ArgumentParser()
# pasted from deepspeed launcher
# https://github.com/microsoft/DeepSpeed/blob/7122362fb025f42dcc1bab40a4211ee626116ce4/deepspeed/launcher/runner.py#L180-L183
parser.add_argument("user_script", type=str, help="User script to launch, followed by any required arguments.")
parser.add_argument("user_args", nargs=argparse.REMAINDER)

args = parser.parse_args()

cmd = ["python", "-u"]
cmd.append(args.user_script)
cmd += args.user_args
print(f"{cmd=}")

# deepspeed launcher essentially does this:
# https://github.com/microsoft/DeepSpeed/blob/7122362fb025f42dcc1bab40a4211ee626116ce4/deepspeed/launcher/runner.py#L571
result = subprocess.Popen(cmd)
result.wait()
```

`program.py` is called by `launcher.py`, which simply print its arguments here:

```python
import sys

print(f"{sys.argv=}")
```

command to run:

```console
$ viztracer -o result.json -- launcher.py program.py --output_dir 123 --other_args abc
cmd=['python', '-u', 'program.py', '--output_dir', '123', '--other_args', 'abc']
sys.argv=['program.py', '--other_args', 'abc']
```

It's clear from the output: `--output_dir` is considered as argument of `program.py` before `Popen`, but it disappears after `Popen`.

It seems that they are parsed as args of `viztracer` during `Popen`, because:

```console
$ viztracer -o result.json -- launcher.py program.py --output_dir 123 -c "print('hello')" --other_args abc
cmd=['python', '-u', 'program.py', '--output_dir', '123', '-c', "print('hello')", '--other_args', 'abc']
hello
```

It surprisingly prints out `hello`

**Expected behavior**

Correctly parse arguments after `--` as args of program.

```console
$ viztracer -o result.json -- launcher.py program.py --output_dir 123 --other_args abc
cmd=['python', '-u', 'program.py', '--output_dir', '123', '--other_args', 'abc']
sys.argv=['program.py', '--output_dir', '123', '--other_args', 'abc']
```

**Environments**

- python: 3.10.12
- viztracer: 0.16.0

**Comment by gaogaotiantian** [comment]
Thank you for reporting this. This is a real issue and will be fixed in #379.
