### ISSUE TITLE
VsCode里右键选择Trace with Viztracer后报错

### ISSUE THREAD

**Issue by JiaYang-Liu** [gaogaotiantian/viztracer#390]
从vscode 扩展中安装Viztracer，然后用pip安装Viztracer后，从工作区右键python文件，选择Trace with Viztracer后报错，Saving trace data, this could take a whileValueError: Can't open file xxx to write

程序是一个示例程序
`def fib(n):
    if n<2:
        return 1
    return fib(n-1)+fib(n-2)

print(fib(10))`

运行结果是89，可以看出程序是运行成功的，但是在生成json文件的时候写入失败了，我尝试了给这个尝试写入的文件夹的权限里加上Everyone 和Users 的完全控制权限，但是并没有解决问题

python版本：3.10.1
pip 安装的Viztracer版本：0.16.1
vscode商店安装的Viztracer版本：v0.2.2
Visual Studio Code版本：1.85.1

![image](https://github.com/gaogaotiantian/viztracer/assets/37820019/31c9b556-fbf7-4699-aaf5-7f8d69c60fc6)

**Comment by gaogaotiantian** [comment]
如果你单纯地做`python -m viztracer XX/temp.py`会报错么？这里大概率是个权限问题。你如果用这个python直接尝试写这个文件能写的进去么？

**Comment by gaogaotiantian** [comment]
Close due to inactivity.
