### ISSUE TITLE
Linux 上 VSCode extension 打开 viztracer 的结果文件出现问题

### ISSUE THREAD

**Issue by FEIFEIEIAr** [gaogaotiantian/viztracer#392]
我是使用VSCode通过SSH远程连接的服务器，出现以下问题（环境在最后）
右键 result.json，点击View with VizTracer后，一直空白（下图右侧）
<img width="1639" alt="90ba915ada9d642ffb52796c40c046a" src="https://github.com/gaogaotiantian/viztracer/assets/77225830/5c3aa761-133e-497d-a79b-0fc4ecac93d5">
在点击View with VizTracer后，本地端是能打开 `http://localhost:9001/ ` ，正常查看的

使用`vizviewer ./result.json`也能正常查看

同样的 result.json 在 Windows 端的 VSCode 上也能正常打开
<img width="812" alt="2825e1d8fd51d97b8206cd99d7a5b5d" src="https://github.com/gaogaotiantian/viztracer/assets/77225830/f9a70b92-015f-4884-9611-485878849e48">

我是使用VSCode通过SSH远程连接的服务器
json文件大小10M左右
该错误始终出现

Environments:
+ VSCode v1.85.1
+ VSCode SSH Remote Extension v0.86.0
+ VizTracer VS Code v0.2.2
+ viztracer 0.16.1                   
+ local OS: Windows 11
+ 服务器 OS: CentOS Linux release 7.9.2009 (Core)

**Comment by gaogaotiantian** [comment]
这个和#387大概率是一个问题——你尝试了手动forward port么？这里可能是需要处理一下，但是我现在人在国内，得回到家里之后才有时间去试一下，我没怎么用过remote server。

**Comment by FEIFEIEIAr** [comment]
> 这个和 #387 大概率是一个问题——你尝试了手动forward port么？这里可能是需要处理一下，但是我现在人在国内，得回到家里之后才有时间去试一下，我没怎么用过remote server。

感觉应该是port的问题，应该是9001端口有什么进程占用了。我在后面一段时间的使用中都没有发生这个 issue 里面的问题了。
我今天试了一下：
1、如果先在 terminal 里使用 `vizviewer ./result.json` ，再右键 result.json，使用 View with VizTracer ，就会一直没响应。（就是这个issue的情况）
 2、先右键 result.json，使用 View with VizTracer ，再在 terminal 里使用 `vizviewer ./result.json` 。会报错 `Error! Port 9001 is already in use, try another port with "--port"`

所以说，应该是默认 port被占用，View with VizTracer 报错了。

是否可以通过以下几个方法解决呢？ 
1、View with VizTracer 出现报错时应该做出提示。
2、如果不指定 port 的情况下自动去寻找没有被占用的 port。

如果方便的话可以告诉这些逻辑在代码的哪些位置吗？我会尝试添加这些功能

**Comment by gaogaotiantian** [comment]
这个逻辑已经存在了。你还是用的remote server吧？这是一个forwarding的问题，如果你都是本地的port，是可以正常工作的。你可以试一下。port forwarding这个部分有个新patch，我感觉好像是对的，我会apply一下。

**Comment by gaogaotiantian** [comment]
我把这个patch发布到0.2.3了，你可以试着更新一下patch看看是不是work。
