### ISSUE TITLE
please provide conda package for the latest version of viztracer

### ISSUE THREAD

**Issue by sergeykk** [gaogaotiantian/viztracer#396]
not sure if this is the right place to ask but in conda forge channel the latest viztracer version is 0.15.6, please provide conda package for 0.16.1

**Comment by gaogaotiantian** [comment]
[@gforsyth](https://github.com/gforsyth/) is the kind person that maintains the conda feedstock. I'm not sure what blocks the build of viztracer 0.16.0+ on conda. I'd be happy to help.

**Comment by gaogaotiantian** [comment]
Conda build is fixed and now has the latest 0.16.3
