### ISSUE TITLE
inline viztraver cannot trace multiprocess

### ISSUE THREAD

**Issue by auderson** [gaogaotiantian/viztracer#405]
test_mp.py:
```code
import viztracer
import multiprocessing

def f():
    import time
    time.sleep(1)

# with viztracer.VizTracer(output_file="trace_mp.json"):
#     p = multiprocessing.Process(target=f)
#     p.start()
#     p.join()
p = multiprocessing.Process(target=f)
p.start()
p.join()

```
With `viztracer test_mp.py`, the log of the child process is reported. But the inline version (commented codes + `python test_mp.py`) cannot capture the child process.
![image](https://github.com/gaogaotiantian/viztracer/assets/48577571/f7f39536-c0f7-41fb-8a74-eedc0b861e9c)
![image](https://github.com/gaogaotiantian/viztracer/assets/48577571/92e35f55-a22f-4f5d-a8f9-54a9d7bc2421)

**Comment by gaogaotiantian** [comment]
This is not a bug. It's by design.

It's not trivial to make inline VizTracer work with multi processing. You'll have to use cmdline version for now if you want full multi process support.

**Comment by auderson** [comment]
> It's not trivial to make inline VizTracer work with multi processing.

I guess so. I tried `viztracer.patch.install_all_hooks()` but it didn't work as expected.

**Comment by gaogaotiantian** [comment]
No it won't work that easily. You need to collect the trace data generated by different processes. There could be ordering issues. VizTracer needs to patch before all the user code executes, and collect all the data after.
