### ISSUE TITLE
可以将在生成文件时自动获取.py的文件名或是加上时间戳么?

### ISSUE THREAD

**Issue by Natural-selection1** [gaogaotiantian/viztracer#408]
你好高天前辈
我是一名学生,目前正在尝试学习python.最近深深地被viztracer所吸引
虽然我并不是很懂调试的那些工具,但是从使用的角度来说,viztracer是一个相当便于理解**"我的程序道理干了什么"**的工具
在这段时间频繁的使用中,我感觉到固定使用**result.json**作为输出文件名并不适合检索时进行区分和管理
虽然可以在使用参数指定文件名,但是每次这样做感觉有些许麻烦

不知道大佬是否愿意添加以下这个功能?
或是存在现有的方式做到如上只是我没有找到?

**Comment by gaogaotiantian** [comment]
没明白什么叫做生成文件时自动获取.py的文件名，是说加一个random string让它不重复么？可选后缀一个timestamp是可以增加的feature，这几天有时间我做一下。

**Comment by Natural-selection1** [comment]
抱歉我的描述不够清晰,应该直接举个例子的(捂脸)
比如: 
 *viztracer example.py*

其生成的文件命不为统一的 
*result.json*

而是类似 *example-result-24-2-23-9-28-34.json* 
这种带有 *被跟踪的.py文件的文件名* + *时间戳* + *result* 这几大特征

1.携带 *被跟踪的.py文件的文件名* 便于在使用 everthing(一种文件检索软件) 时快速检索到
2.携带 *result* 是为了能够一眼看出 *"哦,这个json是我viztracer的结果"* 
3.携带 *时间戳* 是为了便于进行前后比较 和 管理

**Comment by gaogaotiantian** [comment]
我可以加一个optional的cmdline argument去生成这样格式的文件名。但是默认的可能不好改，因为会有backward compatibility的问题。

**Comment by Natural-selection1** [comment]
好的,天哥.
另外,请原谅我在这个不恰当的地方问一下
天哥是否有再详细地介绍Viztracer的想法

毫无疑问Viztracer是一个非常好的工具
但是当我将它推荐给身边的同学的时候,却碍于参考资料太少而只是**放入收藏夹**

作为几乎看完了你所有视频的粉丝
我认为对Viztracer的介绍的视频不是 <***Python分析调试神器【VizTracer】之作者精讲***>
反而是语速匆匆的 <***PyCon China 2020 - 代码理解，从微观到宏观，从功能到性能***>

最近有尝试详尽地了解Viztracer,打算自己来推广一下
但是毕竟还是个只学过一个寒假python的大一学生,还有很多东西没有了解
即使是我自己来介绍肯定是不能完整地介绍出viztracer的所有指令
所以还是来问问原作者是否有这方面的想法

**Comment by gaogaotiantian** [comment]
想把viztracer每个feature都讲一下是一个非常大的工程。对于这种工具来说，大部分的宣传形式都是一个入门使用方案，然后用户觉得好了，再去研究。我目前没有任何做特别详尽的介绍的计划，如果你愿意去以任何方式聊聊viztracer，我是欢迎的。但是viztracer确实有不少相对冷门的feature……
