### ISSUE TITLE
Report Builder Bug

### ISSUE THREAD

**Issue by yilin412** [gaogaotiantian/viztracer#412]
`report_builder.py` line 77:  `except json.JSONDecodeError` 

`json` is not imported when user has `orjson` installed. 

Btw, this bug was found when using `multiprocessing.Pool` on Windows. I guess the exception here is what you called "there’s no way to gracefully catch the exit of the process."

**Comment by gaogaotiantian** [comment]
Ah, interesting. Yes, there's nothing we can do to make `multiprocessing.Pool` work with viztracer. The bug however, is real, we should not catch `json.JSONDecodeError` when we are using orjson.
