### ISSUE TITLE
VizTracer 能否可视化python 模块和类之间的调用关系,在分析不熟悉的项目时很有用?  类似于开源库pyan(已经停止维护了)

### ISSUE THREAD

**Issue by Luck-xgy** [gaogaotiantian/viztracer#418]
![image](https://github.com/gaogaotiantian/viztracer/assets/59566791/2cfc2f02-014f-4a06-9c6c-1e81817e3ccd)

**Comment by gaogaotiantian** [comment]
call graph这种东西，但凡程序稍微复杂一点，就是一坨乱麻，该不懂的依然看不懂。它没有时序关系，包含了大量无效信息。其实这个图本质上就是一个flamegraph，只不过每个function一样大了。你可以试一下viztracer的flamegraph功能，就是不包含时序信息的调用栈。

**Comment by Luck-xgy** [comment]
谢谢耐心解答,没想到call graph不适用复杂程序,目前我只会写些小脚本 .  我会去试一下viztracer的flamegraph功能的.
