### ISSUE TITLE
use `https://ui.perfetto.dev` instead of vendored html.

### ISSUE THREAD

**Issue by adamwojt** [gaogaotiantian/viztracer#426]
First of all, love the tool! Thanks.

I've noticed that when opening traces with `vizviewer` the performance is significantly worse than when loading them up to https://ui.perfetto.dev. There is actually python script provided by perfetto that allows to load up traces into official UI url: https://github.com/google/perfetto/blob/master/tools/open_trace_in_ui and I've been using it instead of vizviewer.

Wonder if this is something worth investigating, since I suppose that version v37 (vizviewer) vs v42 (official URL) make a great difference. Any reason why you decided to vendor the html file instead?

**Comment by gaogaotiantian** [comment]
For a while, the official perfetto does not allow opening a trace file through http for security reasons. Things might have changed by now, but that's not the major reason why I had a vendored perfetto.

The perfetto vizviewer uses is actually customized. If you use vizviewer, you'll find that the source code of the function is displayed on the right bottom when you click on a specific function. If you are using VSCode extension, double click the function will open the corresponding file and scroll to the lines in VSCode. Those are features that are critical but will never be provided by Perfetto. Another thing is the flamegraph - perfetto does not support it well last time I checked.

What kind of performance did you observe that is worse? The time before opening the browser? The time after the browser is opened before the trace is fully loaded? Or the ability to zoom in & out? I doubt it's the version - Perfetto updates very frequently so v37 and v42 might not have that much a difference. (Of course there might be a very important patch in between to significantly improve the performance, I'd be a little surprised if they can do that).

I suspect the performance difference you observe is the time for vizviewer to parse the json file to do some customized stuff - which has nothing to do with Perfetto.

That being said, you'll always have the option to use the original (and up to date) Perfetto if you don't want the fancy feature, but I believe the customized Perfetto is often more helpful in the actual debugging/profiling (at least for me).

**Comment by gaogaotiantian** [comment]
Oh another catch for using the compiled version - you don't need the access to the internet to use it. Yes the official Perfetto can be used without internet once cached, but it still requires internet connection at least once. Might not be a huge factor for most developers, but it is useful for people with limited network resource due to different reasons (for example, security).

**Comment by adamwojt** [comment]
I did not notice the function source code 🤦🏻  That is definitely useful feature and justifies fully the vendoring.

The performance difference I noticed is general navigation speed / zooming in / out.

Thank you for explaining your reasoning, this can be closed as this was more of a question really :)

**Comment by gaogaotiantian** [comment]
If there's a performance difference in navigating then yeah probably that's caused by the versions. I normally update Perfetto version for every minor version for VizTracer and we will see if the next update fixes it.
