### ISSUE TITLE
VizTracer not tracing some functions

### ISSUE THREAD

**Issue by arbenede** [gaogaotiantian/viztracer#439]
I am using `@log_sparse(stack_depth=8)` to trace a couple of functions (say `fun1()`, `fun2()`) however only some of the functions called by `fun1()` and `fun2()` are traced. I am using 
```
tracer = VizTracer(log_sparse=True)
    tracer.start()
    fun1()
    fun2()
    tracer.stop()
 ```
 Is there a way to force `VizTracer` log all the functions called up to the specified `stack_depth`?

**Comment by gaogaotiantian** [comment]
Can you provide a minimum reproducible example? What's your code and why you think it did not work properly? There's not much information in the description so I don't know where to look.
