### ISSUE TITLE
Build wheels for free-threading version

### ISSUE THREAD

**Issue by gaogaotiantian** [gaogaotiantian/viztracer#440]
3.13 now has unofficial free-threading version and cibuildwheels seems to support it. Let's make wheels for it and see how it works.

**Comment by KRRT7** [comment]
when installing on 3.13t i get this error
```
      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/

      Checking for Rust toolchain....
```
wheels would be appreciated :)

**Comment by gaogaotiantian** [comment]
I doubt that has anything to do with viztracer. Viztracer does not have dependency on rust. Unless you are installing the full version with `orjson`.

**Comment by KRRT7** [comment]
> I doubt that has anything to do with viztracer. Viztracer does not have dependency on rust. Unless you are installing the full version with `orjson`.

i didn't stop to consider that, apologies, yes i'm installing the full version with orjson, `pip install orjson` results in the same message, sorry for the noise

**Comment by gaogaotiantian** [comment]
We are building 3.13t wheels now with #479

**Comment by dan-glass** [comment]
```
Fatal Python error: Segmentation fault

Current thread 0x00007f7a40c70740 (most recent call first):
  File "/usr/local/lib/python3.13t/dist-packages/viztracer/tracer.py", line 261 in stop
  File "/usr/local/lib/python3.13t/dist-packages/viztracer/viztracer.py", line 189 in stop
...
  File "/usr/lib/python3.13/threading.py", line 363 in wait
  File "/usr/lib/python3.13/threading.py", line 659 in wait

Extension modules: viztracer.snaptrace, viztracer.vcompressor (total: 2)
```
Can reproduce every time, but not with debug version of Python, nor with valgrind.
