### ISSUE TITLE
[optimize] always add quotes when printing file path

### ISSUE THREAD

**Issue by FunnySaltyFish** [gaogaotiantian/viztracer#441]
I'm a new user for `viztracer`, when using the project, I found a small improvement.

Currently, the report builder will add quotes when there is space in the file path, as shown in the code below, due to https://github.com/gaogaotiantian/viztracer/issues/324:

```python
# src/viztracer/report_builder.py
if " " in report_abspath:
    color_print("OKGREEN", "vizviewer \"{}\"".format(report_abspath))
else:
    color_print("OKGREEN", "vizviewer {}".format(report_abspath))
```

However, when I using the `Git Bash` on `Windows`, the separator will be `\`, which will be considered as escape symbol in git bash. The command like: `vizviewer D:\python\result.json` will throw `File D:pythonresult.json does not exist!` error. By simply adding the quotes, we can solve the problem: `vizviewer "D:\python\result.json"`. This new command is valid for `git bash`, `powershell` and `cmd`.

So i'm wondering whether it's better to add quotes for all output paths, no matter there contains spaces or not. Or if there are some reasons not to do so. I'm glad to give a PR for it. Thanks.

**Comment by gaogaotiantian** [comment]
Quotes look bad... I'd prefer not to always add quotes around the path. Git bash is a relatively rare environment - it uses bash but also windows path? That fact by itself is a bit complicated.

**Comment by FunnySaltyFish** [comment]
Referring to what discussed in #442, I'll also close this issue. Thanks for replying.
