### ISSUE TITLE
Is it possible to record the function in which tracer is stopped?

### ISSUE THREAD

**Issue by petergtz** [gaogaotiantian/viztracer#443]
Say I have the following code:
```python

def g():
    pass

def f():
    g()
    get_tracer().stop()
    get_tracer().save(...)

tracer = VizTracer()
tracer.start()
f()
```
The trace file will now only list `g()`, but not `f()`, because `f` hasn't finished yet at the time of stopping the tracer. Is there a way in viztracer to still record `f` even though it's still in progress? This would be useful in cases where we only want to trace the beginning of a long-running process.

<img width="518" alt="Screenshot 2024-06-11 at 13 32 19" src="https://github.com/gaogaotiantian/viztracer/assets/3618401/e04fee76-2239-4938-a819-dac3649afc47">

**Comment by gaogaotiantian** [comment]
I found a way to do that. Now the unfinished function will be flushed. It will be released in the next version but in the meantime you can try it out with `pip install git+https://github.com/gaogaotiantian/viztracer`

**Comment by petergtz** [comment]
Wow, that's great! Thank you so much!
