### ISSUE TITLE
Can't install on LinuxMint 19.3

### ISSUE THREAD

**Issue by Marek-Moehling** [gaogaotiantian/viztracer#45]
LinuxMint 19.3 (tricia) 
	GNOME: 3.28.2 (Ubuntu)
	Kernel version: 5.4.0-53-generic (#59~18.04.1-Ubuntu SMP Wed Oct 21 12:14:56 UTC 2020)
	GCC: 7 (x86_64-linux-gnu)
	Xorg: 1.19.6 (15 September 2020  07:40:51AM)

    xx@xx:~$ pip install viztracer
    Collecting viztracer
      Downloading https://files.pythonhosted.org/packages/67/28/a2e5f44447beeb4957f984d3e6f58339d8352a76b71c9a6e670528539795/viztracer-0.10.1.tar.gz (678kB)
        100% |████████████████████████████████| 686kB 818kB/s 
    Building wheels for collected packages: viztracer
      Running setup.py bdist_wheel for viztracer ... error
      Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-xmeib9s6/viztracer/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp0f5oxn44pip-wheel- --python-tag cp36:
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.6
      creating build/lib.linux-x86_64-3.6/viztracer
      copying src/viztracer/__init__.py -> build/lib.linux-x86_64-3.6/viztracer
      copying src/viztracer/code_monkey.py -> build/lib.linux-x86_64-3.6/viztracer
      copying src/viztracer/vizcounter.py -> build/lib.linux-x86_64-3.6/viztracer
      copying src/viztracer/functree.py -> build/lib.linux-x86_64-3.6/viztracer
      copying src/viztracer/report_builder.py -> build/lib.linux-x86_64-3.6/viztracer
      copying src/viztracer/util.py -> build/lib.linux-x86_64-3.6/viztracer
      copying src/viztracer/prog_snapshot.py -> build/lib.linux-x86_64-3.6/viztracer
      copying src/viztracer/event_base.py -> build/lib.linux-x86_64-3.6/viztracer
      copying src/viztracer/vizobject.py -> build/lib.linux-x86_64-3.6/viztracer
      copying src/viztracer/__main__.py -> build/lib.linux-x86_64-3.6/viztracer
      copying src/viztracer/main.py -> build/lib.linux-x86_64-3.6/viztracer
      copying src/viztracer/flamegraph.py -> build/lib.linux-x86_64-3.6/viztracer
      copying src/viztracer/tracer.py -> build/lib.linux-x86_64-3.6/viztracer
      copying src/viztracer/decorator.py -> build/lib.linux-x86_64-3.6/viztracer
      copying src/viztracer/simulator.py -> build/lib.linux-x86_64-3.6/viztracer
      copying src/viztracer/viztracer.py -> build/lib.linux-x86_64-3.6/viztracer
      copying src/viztracer/vizlogging.py -> build/lib.linux-x86_64-3.6/viztracer
      creating build/lib.linux-x86_64-3.6/viztracer/html
      copying src/viztracer/html/trace_viewer_full.html -> build/lib.linux-x86_64-3.6/viztracer/html
      copying src/viztracer/html/trace_viewer_embedder.html -> build/lib.linux-x86_64-3.6/viztracer/html
      copying src/viztracer/html/flamegraph.html -> build/lib.linux-x86_64-3.6/viztracer/html
      running build_ext
      building 'viztracer.snaptrace' extension
      creating build/temp.linux-x86_64-3.6
      creating build/temp.linux-x86_64-3.6/src
      creating build/temp.linux-x86_64-3.6/src/viztracer
      creating build/temp.linux-x86_64-3.6/src/viztracer/modules
      x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c src/viztracer/modules/snaptrace.c -o build/temp.linux-x86_64-3.6/src/viztracer/modules/snaptrace.o
      src/viztracer/modules/snaptrace.c:6:10: fatal error: Python.h: No such file or directory
       #include <Python.h>
                ^~~~~~~~~~
      compilation terminated.
      error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
      
      ----------------------------------------
      Failed building wheel for viztracer
      Running setup.py clean for viztracer
    Failed to build viztracer
    Installing collected packages: viztracer
      Running setup.py install for viztracer ... error
        Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-xmeib9s6/viztracer/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-142jjrak-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
        running install
        running build
        running build_py
        creating build
        creating build/lib.linux-x86_64-3.6
        creating build/lib.linux-x86_64-3.6/viztracer
        copying src/viztracer/__init__.py -> build/lib.linux-x86_64-3.6/viztracer
        copying src/viztracer/code_monkey.py -> build/lib.linux-x86_64-3.6/viztracer
        copying src/viztracer/vizcounter.py -> build/lib.linux-x86_64-3.6/viztracer
        copying src/viztracer/functree.py -> build/lib.linux-x86_64-3.6/viztracer
        copying src/viztracer/report_builder.py -> build/lib.linux-x86_64-3.6/viztracer
        copying src/viztracer/util.py -> build/lib.linux-x86_64-3.6/viztracer
        copying src/viztracer/prog_snapshot.py -> build/lib.linux-x86_64-3.6/viztracer
        copying src/viztracer/event_base.py -> build/lib.linux-x86_64-3.6/viztracer
        copying src/viztracer/vizobject.py -> build/lib.linux-x86_64-3.6/viztracer
        copying src/viztracer/__main__.py -> build/lib.linux-x86_64-3.6/viztracer
        copying src/viztracer/main.py -> build/lib.linux-x86_64-3.6/viztracer
        copying src/viztracer/flamegraph.py -> build/lib.linux-x86_64-3.6/viztracer
        copying src/viztracer/tracer.py -> build/lib.linux-x86_64-3.6/viztracer
        copying src/viztracer/decorator.py -> build/lib.linux-x86_64-3.6/viztracer
        copying src/viztracer/simulator.py -> build/lib.linux-x86_64-3.6/viztracer
        copying src/viztracer/viztracer.py -> build/lib.linux-x86_64-3.6/viztracer
        copying src/viztracer/vizlogging.py -> build/lib.linux-x86_64-3.6/viztracer
        creating build/lib.linux-x86_64-3.6/viztracer/html
        copying src/viztracer/html/trace_viewer_full.html -> build/lib.linux-x86_64-3.6/viztracer/html
        copying src/viztracer/html/trace_viewer_embedder.html -> build/lib.linux-x86_64-3.6/viztracer/html
        copying src/viztracer/html/flamegraph.html -> build/lib.linux-x86_64-3.6/viztracer/html
        running build_ext
        building 'viztracer.snaptrace' extension
        creating build/temp.linux-x86_64-3.6
        creating build/temp.linux-x86_64-3.6/src
        creating build/temp.linux-x86_64-3.6/src/viztracer
        creating build/temp.linux-x86_64-3.6/src/viztracer/modules
        x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c src/viztracer/modules/snaptrace.c -o build/temp.linux-x86_64-3.6/src/viztracer/modules/snaptrace.o
        src/viztracer/modules/snaptrace.c:6:10: fatal error: Python.h: No such file or directory
         #include <Python.h>
                  ^~~~~~~~~~
        compilation terminated.
        error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
        
        ----------------------------------------
    Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-xmeib9s6/viztracer/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-142jjrak-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-xmeib9s6/viztracer/

**Comment by gaogaotiantian** [comment]
It looks like your pip did not pick up the wheel file so it used the source file to build and install.

There are two ways that you can go

1. Figure out why it did not pick the wheel file. 
  * ```many_linux2014``` is used for ```viztracer``` wheels.
  * Are you using ```pip >= 19.3```? 
  * When you install other packages, did you successfully locate the ```whl``` file, instead of build it from ```tar```?

2. Fix the build error and just install it from source.
  * I believe the compile error is due to lack of python dev version. (Can't get ```<python.h>``` header)
  * You could do ```sudo apt-get install python3.6-dev``` to install the dev version. (I think LinuxMint is using apt-get, but you should be more familiar with how to install packages)

**Comment by Marek-Moehling** [comment]
> Are you using pip >= 19.3?

No, I had 9.0.1. Updating to 20.2.4 helped, though there was a warning:

    x@x:~/progs/python/ProtonVPNgui/ProtonVPNgui/ProgramName-Version/usr/bin/ProtonVPNgui$ pip install viztracer
    WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
    Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
    To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
    Defaulting to user installation because normal site-packages is not writeable
    Collecting viztracer
      Downloading viztracer-0.10.1-cp36-cp36m-manylinux2014_x86_64.whl (721 kB)
         |████████████████████████████████| 721 kB 1.1 MB/s 
    Installing collected packages: viztracer
    Successfully installed viztracer-0.10.1

**Comment by gaogaotiantian** [comment]
Yeah that explained things. manylinux2014 only supports ```pip >=19.3``` and even manylinux2010 requires ```pip >= 19.0```. The warning you are getting is not ```viztracer``` related, it's probably about setup of your pip. At this point I'm not 100% sure why this happened. However, I would recommend using virtualenv for your project and that might clear things a lot.

Anyway, I believe the ```viztracer``` related issue is solved so I'll close this issue :)
