### ISSUE TITLE
关于长时间记录监控线程导致记录过多的问题

### ISSUE THREAD

**Issue by RedSiamese** [gaogaotiantian/viztracer#451]
高老师你好

在我的python代码中存在一个监控线程，每隔2秒记录一次当前运行状态，监控线程运行函数如下，类似于

```
    def record(self):
        while not self.__exit:
            now = time.monotonic_ns()
            for task in self.record_tasks:
                task(now)
            self.now = now
            time.sleep(2)
```

其中record_tasks是注册的监控函数列表

同时，我使用viztracer对堆栈状态进行记录

整个程序需要运行超过1.5小时，由于viztracer会忠实记录监控线程的堆栈信息，导致最终的保存结果极大（超过200M），但是其中绝大部分记录，是对监控线程的记录，实际没有作用。

我尝试通过 viztracer.ignore_function 装饰 record 函数，但是他仅仅忽略了record这一层堆栈，在这个函数中运行的其他函数堆栈仍然会被记录

请问遇到这种情况应该如何忽略整个 record函数及其中的调用？

或者是否能够有类似于 viztracer.ignore_this_thread 标识，在某个线程中运行注册该标识后，该线程的信息不会被记录？

**Comment by gaogaotiantian** [comment]
`ignore_function`理论上应该不记录这个函数和它call的所有子函数，如果不是的话，说明哪里写错了……如果你有一个可以repro的minimum代码我可以看一下。

**Comment by RedSiamese** [comment]
我简化了一下我的代码，大概是这样的

```
from concurrent.futures import ThreadPoolExecutor as thread_pool
import time
import viztracer

class record:
    def __init__(self, info_path:str = './info_record.json') -> None:
        self.viz:'viztracer.VizTracer|None' = viztracer.VizTracer(output_file=info_path)
        self.tasks = []

    def __enter__(self):
        self.__exit = False
        self.__record()
        self.__record_thd = thread_pool(1)
        self.__record_thd.submit(self.record)
        self.viz.__enter__()

    def __exit__(self, exc_type, exc_value, traceback):
        self.__exit = True
        self.viz.__exit__(exc_type, exc_value, traceback)
        
    @viztracer.ignore_function
    def record(self):
        while not self.__exit:
            now = time.monotonic_ns()
            for task in self.tasks:
                task(now)
            self.now = now
            time.sleep(0.2)

    def __record(self):
        self.tasks.append(lambda x: x)

with record():
    time.sleep(1)

```

**Comment by RedSiamese** [comment]
很抱歉当前我的开发环境不能直接上次文件，所以代码和记录的结果无法以文件的形式给出，只能以文本形式贴在上面

**Comment by RedSiamese** [comment]
上述代码中，将record函数作为线程函数进行调用，使用```@viztracer.ignore_function```进行装饰，在其中调用的如time.sleep(0.2)、lambda函数等依然会被记录。

viztracer版本是0.16.2，python版本3.8.3

**Comment by RedSiamese** [comment]
我看了一下文档是不是因为只使用@viztracer.ignore_function不填viztracer.ignore_function的参数只对globally registered tracer起作用

**Comment by gaogaotiantian** [comment]
这里有个竞争冒险的问题。
```python
        self.__record_thd.submit(self.record)
        self.viz.__enter__()
```
这两个东西不一定谁先运行，如果self.record先运行，就会跳过暂停。这可能可以算是viztracer的一个bug，但是viztracer一般的用法是通过command line来执行，这种inline的因为viztracer可以掌控的东西太少了，所以很可能有各种各样的问题。

暂时的解决办法也很简单，你把这两行位置换一下就行了，确保在submit之前，viztracer已经start了。

**Comment by RedSiamese** [comment]
使用这个修改可以成功忽略record函数中的函数记录了，非常感谢！

在最终记录的文件中，会记录一点在这个线程刚开启时候的一些系统函数，通过把代码改成
```
@viztracer.ignore_function
    def __enter__(self):
        self.__exit = False
        self.__record()
        self.__record_thd = thread_pool(1)
        self.viz.__enter__()
        self.__record_thd.submit(self.record)
```
也无法直接完全忽略对这条线程的记录

请问是否有办法在运行时记录，或者在最终生成记录文件时，忽略这整个线程？

**Comment by gaogaotiantian** [comment]
暂时没有一个方法去filter out threads。目前的设计还不是特别支持。不过在未来会考虑这个功能，看起来是有意义的。

**Comment by RedSiamese** [comment]
好的，我后面尝试一下，在VizTracer.__exit__之后对生成的文件进行编辑实现这个功能

我的一个想法是或许可以在线程中运行一个类似于 viztracer.ignore_this_thread，增加一个标识，将之前的记录删掉（或者不删，后面直接不写进文件），然后后续运行时不再记录，写进文件时也不再写入该线程的信息进入文件。不过感觉有点不优雅，比如调用之后删除之前对该线程的记录就有点傻。或许还有很多别的需要考虑。

总之非常感谢。

**Comment by gaogaotiantian** [comment]
“找到之前的记录”和“最终不写入”都是有难度的事情。在线程开始之后再说这个线程的数据我不要，是比较麻烦而且不科学的，就算实现估计也是想办法从最开始就不记录数据。

**Comment by RedSiamese** [comment]
确实，或许可以给开启线程的函数添加一个装饰器
```
thp = ignore_thread(ThreadPoolExecutor)(1)
```
在ignore_thread中的函数生成的线程不进行记录？
我尝试一下我在viz外部能不能实现类似于这样的方式

**Comment by gaogaotiantian** [comment]
executor的控制难度是比较大的，因为你只能pass in task。

**Comment by RedSiamese** [comment]
我观察到在viztracer C code中，linux版本的线程id的获取是通过snaptrace.c中snaptrace_createthreadinfo函数中的syscall(SYS_gettid)获取的，这个和python中的threading.get_ident()获取的线程id并不一致

所以我编译了一个模块提供了一个get_tid()函数使用syscall(SYS_gettid)获得了和viztracer中相同的tid

通过以下代码（这段代码不能运行，其中的libmy_test是我在自己环境中编译的一个c扩展模块）
```
from concurrent.futures import ThreadPoolExecutor as thread_pool
import time, json
import viztracer
import libmy_test

'''
// libmy_test
int get_tid() {
    return syscall(SYS_gettid);
}
'''

def get_tid(info = None):
    def get_tid_impl(func = None):
        def wapper(*args, **kwargs):
            import threading
            nonlocal info
            if info is not None:
                print(threading.get_ident())
                print(threading.current_thread())
                print(libmy_test.get_tid())
                info.add(libmy_test.get_tid())
            return func(*args, **kwargs)
        return wapper
    return get_tid_impl


class record:
    tid = set()

    def __init__(self, info_path:str = './info_record.json') -> None:
        self.info_path = info_path
        self.viz:'viztracer.VizTracer|None' = viztracer.VizTracer(output_file=info_path)
        self.tasks = []

    def __enter__(self):
        self.__exit = False
        self.__record()
        self.__record_thd = thread_pool(1)
        self.__record_thd.submit(self.record)
        self.viz.__enter__()

    def __exit__(self, exc_type, exc_value, traceback):
        self.__exit = True
        self.viz.__exit__(exc_type, exc_value, traceback)
        with open(self.info_path, 'r+') as f_info:
            info:dict = json.load(f_info)
            info['traceEvents'] = list(filter(lambda d:d["tid"] not in self.tid, info['traceEvents']))
        with open(self.info_path, 'w+') as f_info:
            json.dump(info, f_info)
        print(self.tid)
        
    
    @viztracer.ignore_function
    @get_tid(info = tid)
    def record(self):
        while not self.__exit:
            now = time.monotonic_ns()
            for task in self.tasks:
                task(now)
            self.now = now
            time.sleep(0.2)

    def __record(self):
        self.tasks.append(lambda x: x)

with record():
    time.sleep(1)
```
通过把线程id保存入对象，在VizTracer.__exit__之后去掉所有"tid"在保存的tid中的堆栈记录，如果把某个和这有关的函数作为过滤条件传给viztracer，或许可以阻止viztracer在生成文件时记录相应的记录。

这个方法确实很不科学，使用线程池时，任务甚至无法确定是那条线程运行的，也不能保证屏蔽到线程池中所有线程，希望可以有更好的解决方案

**Comment by RedSiamese** [comment]
不过，通过传入viztracer写记录文件时的过滤条件，可能是一个相对科学一点的方案。因为这个无关viztracer运行时对堆栈记录本身，而让使用者来决定过滤条件，过滤最终生成的记录文件。

在本例中，viztracer可以照常记录，不用关心获取线程id的问题，只要使用者能获取到线程id，并传给viztracer进行过滤就行。

**Comment by RedSiamese** [comment]
另外，对于viztracer中获取的线程id使用的是c code，无法和python中的threading.get_ident()对齐的问题，可能会对使用者在后续分析记录文件时产生困扰。

这个问题是否需要考虑以下
