### ISSUE TITLE
traced script option parsing is broken

### ISSUE THREAD

**Issue by superlopuh** [gaogaotiantian/viztracer#455]
I would like to trace the time it takes to run `my_cli.py --version` with vistracer, but it just print the viztracer version. From the help, it's not obvious what the correct way to pass the arguments would be. when I call `viztracer "my_cli.py --version"`, it says `No such file`. How do I pass arguments to my command and have the trace using viztracer?

**Comment by gaogaotiantian** [comment]
> It’s possible that there’s a conflict or an ambiguity. viztracer takes -- as a separator between arguments to viztracer and positional arguments to your script.
> `viztracer -o result.json -- my_script.py -o output_for_my_script.json`

So in your case, it should be `viztracer -- my_cli.py --version`

**Comment by superlopuh** [comment]
Works beautifully, thank you. Could you please add this to the readme or `--help`?

**Comment by gaogaotiantian** [comment]
This is a very standard technique on Linux CLI tools I believe, not specific to viztracer.

**Comment by superlopuh** [comment]
Ah, I didn't realize. It might still be worth adding it to the help in your tool to make it more discoverable for people new to unix?

**Comment by gaogaotiantian** [comment]
It is in the documentation - https://viztracer.readthedocs.io/en/latest/basic_usage.html#command-line
