### ISSUE TITLE
log_sparse=True is not propagated to subprocesses when using multiprocessing with spawn

### ISSUE THREAD

**Issue by behzad-a** [gaogaotiantian/viztracer#463]
When `log_sparse=True`, I expected it to propagate to all subprocesses. However, when we use multiprocessing with `spawn` as the start method, everything is traced. See the example below:

```python
# test.py
# cmd: viztracer --log_sparse -- test.py

import multiprocessing
import multiprocessing.pool
from viztracer import get_tracer

def foo(idx):
    print(f"foo_{idx}")

def bar(idx):
    print(f"bar_{idx}")

def child(idx):
    foo(idx)
    with get_tracer().log_event(f"custom_event_{idx}"):
        bar(idx)

def main():
    with multiprocessing.pool.Pool(
        2,
        context=multiprocessing.get_context('spawn'),
    ) as pool:
        pool.map(child, range(10))

if __name__ == "__main__":
    main()
```

which produces the following trace:
![Screenshot 2024-08-08 at 10 47 17 AM](https://github.com/user-attachments/assets/63034349-cc7e-4dbc-b991-cf25451bf95c)

As you can see, everything is being traced whereas I only expected `custom_event` to show up. If we use anything other than `spawn`, it works fine:
![Screenshot 2024-08-08 at 10 50 34 AM](https://github.com/user-attachments/assets/cf80b733-31a3-4d4e-9919-e92d92156594)

I believe the issue is that when using Spawn, we always start tracing regardless of the `log_sparse` option. More specifically, see https://github.com/gaogaotiantian/viztracer/blob/5495e8963297e339dd498c9ceb6b288011181915/src/viztracer/patch.py#L160.

**Comment by gaogaotiantian** [comment]
I'm not around my dev machine recently. In theory the argument should be passed to spawned process. I'll need to take a look at this later (in about a week or two).

**Comment by gaogaotiantian** [comment]
Sorry it took me a while. Thank you for the issue and I already fixed the issue. The next release should be soon.
