### ISSUE TITLE
print class name with member function

### ISSUE THREAD

**Issue by noisystreet** [gaogaotiantian/viztracer#469]
can viztracer show class name along with member function calls when tracing some code？

**Comment by gaogaotiantian** [comment]
Yeah at this point `co_qualname` probably is preferred than `co_name`. I'll use `co_qualname` will actually contains the class information you mentioned.

**Comment by gaogaotiantian** [comment]
Ah, I realized that this field is not added until 3.11. I guess we can generate different results for different Python versions that's fine. 3.10 will be eol in about 2 years and we will have a consistent behavior then.
