### ISSUE TITLE
Are Cython (.pyx) files not traced ?

### ISSUE THREAD

**Issue by print-sid8** [gaogaotiantian/viztracer#472]
Hi just wanted to understand if Viztracer can trace and see which parts of .pyx file is used.

_rasterize is a function within _features.pyx , and it is used very frequently in features.py file here - https://github.com/rasterio/rasterio/tree/main/rasterio , but it's not captured in the trace and the visualization.

I would be good to know if viztracer can track these modules and functions somehow, thanks!

**Comment by gaogaotiantian** [comment]
If the function call can't be picked up by `sys.setprofile`, it can't be traced. I'm not a Cython user but I'm not surprised if Cython does not support `sys.setprofile` for its functions - it's not Python.

**Comment by print-sid8** [comment]
Great thanks for the info!

**Comment by auderson** [comment]
@gaogaotiantian 
Wondering if we can detect C functions in py3.13 using the new monitoring feature?

**Comment by gaogaotiantian** [comment]
`sys.monitoring` does not give extra information about function calls.
