### ISSUE TITLE
"Segmentation fault" when importing torch

### ISSUE THREAD

**Issue by loicmagne** [gaogaotiantian/viztracer#486]
Ubuntu 24.04, Python 3.12.3, torch 2.4.0+cu124
Simply having `import torch` in a test.py file, and using `viztracer test.py` gives me: `Segmentation fault (core dumped)`

**Comment by gaogaotiantian** [comment]
Ah, I knew I saw this somewhere. This was a bug in CPython (https://github.com/python/cpython/issues/122029) and was actually fixed by myself.. 3.12.5+ should work.

**Comment by gaogaotiantian** [comment]
I agree segfault is probably not the way to go even if this is a bug of CPython, but we do have some assumptions in VizTracer (for example, a `c_return` always corresponds to a `c_call`, not a `call`), and if those assumptions are broken by CPython, we can't really figure out what's going on. So at this time, maybe just upgrade CPython?
