### ISSUE TITLE
Small annoyance url is not clickable in terminal

### ISSUE THREAD

**Issue by maartenbreddels** [gaogaotiantian/viztracer#49]
The trailing dots cause smart terminal to misread the URL. If a space is between it, users can click it.
```
Saving report to /Users/maartenbreddels/src/ipython/traitlets/result.html...
Saving report to /Users/maartenbreddels/src/ipython/traitlets/result.html...
```

E.g.
```
Saving report to /Users/maartenbreddels/src/ipython/traitlets/result.html ...
Saving report to /Users/maartenbreddels/src/ipython/traitlets/result.html ...
```

**Comment by gaogaotiantian** [comment]
That is something I can fix in master. I probably won’t make a new release just about that. In the meantime, you could probably try `--open` option.

**Comment by gaogaotiantian** [comment]
This is fixed on https://github.com/gaogaotiantian/viztracer/commit/6b9bfa1c20f9f088cb077ab710a6aac8325f7a3d

It will take effect in next release.

**Comment by maartenbreddels** [comment]
Great, thanks, didn't know about open actually.
