### ISSUE TITLE
Viztracer result becomes wrong after some pytorch function call with `exclude_files`

### ISSUE THREAD

**Issue by FindDefinition** [gaogaotiantian/viztracer#508]
## Environment

torch 2.5.1, python 3.11.10, ubuntu 22.04

## Problem

I don't need trace results inside `torch.export` module, so I use `exclude_files` to ignore it. The problem is if I trace with `exclude_files`, after calling `torch.distributed.pipelining.pipeline`, trace result of following calls only keep stack depth <= 4 result.

with `exclude_files`:
![image](https://github.com/user-attachments/assets/ca92be91-6b92-46c8-835c-8d80bf0ee59b)

without `exclude_files`:
![image](https://github.com/user-attachments/assets/b19fd8d4-9605-4cb7-ad27-0e8fcbe50f3d)

## Reproduce

1. install pytorch >= 2.5

2. get `exclude_files` by `import torch.export; print(torch.export.__file__)`

3. launch viztracer with following script and command:

```Python
import torch
import torch.export 
from torch.distributed.pipelining import pipeline
from torch.distributed.pipelining import SplitPoint
in_dim = 16
C = 64
HIDDEN = 256
layer_dims = [C] * 8
out_dim = 10
STAGE = 8


class MyNetworkBlock(torch.nn.Module):
    def __init__(self, in_dim, out_dim):
        super().__init__()
        mid_dim = HIDDEN
        self.lin1 = torch.nn.Conv2d(in_dim, mid_dim, 3, padding=1)
        self.lin2 = torch.nn.Conv2d(mid_dim, mid_dim, 3, padding=1)
        self.lin3 = torch.nn.Conv2d(mid_dim, out_dim, 3, padding=1)

    def forward(self, x):
        x = self.lin1(x)
        x = torch.relu(x)
        x = self.lin2(x)
        x = torch.relu(x)
        x = self.lin3(x)
        x = torch.relu(x)
        return x

class MyNetwork(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.num_layers = len(layer_dims)

        prev_dim = in_dim
        for i, dim in enumerate(layer_dims):
            super().add_module(f"layer{i}", MyNetworkBlock(prev_dim, dim))
            prev_dim = dim
        self.output_proj = torch.nn.Conv2d(layer_dims[-1], out_dim, 3, padding=1)

    def forward(self, x):
        for i in range(self.num_layers):
            layer = getattr(self, f"layer{i}")
            x = layer(x)

        return self.output_proj(x)

print(torch.export.__file__)
example_input = torch.randn(16, in_dim, 240, 320)

split_spec = {}
for j in range(STAGE - 1):
    split_spec[f"layer{j}"] = SplitPoint.END


pipe = pipeline(MyNetwork(), mb_args=(example_input,), split_spec=split_spec)

# after pytorch pipeline, the trace result (stack depth) of viztracer becomes wrong,
# we can only see results with stack depth <= 4.
class A:
    def a(self):
        print("a")
        self.b()
    def b(self):
        print("b")
        self.c()
    
    def c(self):
        print("c")
        self.d()
    def d(self):
        print("d")
        self.e()
    def e(self):
        print("e")
        # self.f()

a = A()
a.a()
```

```Bash
viztracer --exclude_files /path/to/torch/export --max_stack_depth 15 /path/to/script.py

```

**Comment by gaogaotiantian** [comment]
Which version of viztracer are you using? I can't repro this on 3.12, the stack looks fine. To be honest, I don't recommend the `--exclude_files` command for heavy filtering. The command itself has a relatively large overhead. It's helpful for understanding the code, but might be a bit slow for profiling.

**Comment by FindDefinition** [comment]
I tried on python 3.11/3.12 on Mac OS, this problem exists on python 3.11, OK on 3.12.
I convert result from viztracer to tree view and tree filtering to analysis complex project such as PyTorch, the tree filtering is done in frontend and become slow if number of entries larger than 100000, so I need `exclude_files ` to reduce size. Another option is remove them after tracing, maybe slower than `exclude_files` since your code handle this in C.

**Comment by gaogaotiantian** [comment]
Okay it only repros on 3.11, interesting. I can try to repro it and see if it's a VizTracer issue. For the latest version of Perfetto, you can just select the part you need and do a flamegraph, not sure if it's helpful. Removing after tracing is not as fast, but it does not use your program time so your result would be more accurate. If you can narrow down your interest area, `log_sparse` would be very helpful to reduce the entries.

**Comment by gaogaotiantian** [comment]
I believe I found the issue, and I'll fix it soon.
