### ISSUE TITLE
Torch events have wrong time offset on certain machines

### ISSUE THREAD

**Issue by Technohacker** [gaogaotiantian/viztracer#529]
Hey!
I've tried recording Torch events with `log_torch`, but for some machines the Torch events are wildly offset from the VizTracer events, often by a factor of 300 to 5,000 hours or so.

My hunch is the uptime of the machine may have a factor (indirectly. My primary suspect is the monotonic clock), since the below trace was obtained from a machine with ~240 days of uptime. I had another trace on a machine with ~190 days of uptime which had a less-prominent shift

VizTracer: 1.0.0
Python: 3.10.4
PyTorch: 2.5.1

![image](https://github.com/user-attachments/assets/522f168f-f58e-4235-8466-0c1ebd7b29c7)
![image](https://github.com/user-attachments/assets/fbc13f42-6b5e-4da2-bbdf-4284ac040c4e)
![image](https://github.com/user-attachments/assets/e578e6da-17b3-4d72-a936-b73f1238f367)

**Comment by Technohacker** [comment]
Currently unable to test it on a freshly booted system since I can't have the cluster nodes restarted :sweat_smile:

**Comment by gaogaotiantian** [comment]
Yeah, 200 days would overflow viztracer's calibration. I'll take a look into it.

**Comment by Technohacker** [comment]
I assume it's related to these lines in particular? https://github.com/gaogaotiantian/viztracer/blob/0cf76940195dd87c38ae17aac0fc61133bfbbfcb/src/viztracer/modules/quicktime.c#L145-L150

I can have a go at it and prepare a patch if needed!

**Comment by gaogaotiantian** [comment]
Yeah. My thought is to calculate `t0_ts` and `t0_ns` after collecting all `start_*`. If the first timestamp is greater than say `0x0001_0000_0000_0000`, then we minus this number before sum (notice that you can't change the `start_*` as they will be used later). Then we calculate the average with the minused number, and add back that constant. This should avoid overflow.

**Comment by Technohacker** [comment]
What I had in mind was to do the division right away (like `t0_ts += start_ts[i] / CALIBRATE_SIZE`), instead of accumulate and divide, though maybe we'd have to account for the remainder of that division separately

**Comment by gaogaotiantian** [comment]
I wanted to keep the array of starts as close as possible, so less computation in the loop would be nice.

Yes you can post-calculate with this, divide and accumulate. Also have another temp variable to accumulate the remainder, and divide that remainder accumulation by `CALIBRATE_SIZE` at the end - that would work.

**Comment by Technohacker** [comment]
Sounds good! I'll test it out and let you know

**Comment by Technohacker** [comment]
I've confirmed it works, I'll make a PR for it now. As an aside, I did end up getting the node rebooted and it still hadn't lined up correctly, so I think there were overflows regardless of uptime :sweat_smile:

**Comment by gaogaotiantian** [comment]
Hmm, I think it depends on the implementation of the monotonic clock. I believe it should start from 0 when the computer is rebooted. Did you reboot the physical machine or it's a VM? It's possible the reboot did not reset the timer. Anyway, it should be resolved with this new method.

**Comment by Technohacker** [comment]
It's a physical machine as far as I can tell, and yeah I've only been able to reboot it from Linux rather than a cold-reset. That might explain it :thinking:
