### ISSUE TITLE
Jupyter Notebook integration

### ISSUE THREAD

**Issue by maartenbreddels** [gaogaotiantian/viztracer#64]
Have you thought about Jupyter notebook integration, similar to https://jiffyclub.github.io/snakeviz/ ?

**Comment by gaogaotiantian** [comment]
I think other people asked about Jupyter. There are several reasons that I have not done this(or made any effort towards it)

* Personally I never use Jupyter
* It requires chromium for the UI to work and the UI is super heavy
* The UI shows in a standalone html, which may work with iframe, but I'm not sure
* People who use Jupyter are generally less concerned about performance. When they do, it's often a numpy issue which VizTracer is not helpful

However, if someday someone comes up with a solution on Jupyter, I would love to check it out and investigate the possibility to make it official.

**Comment by gaogaotiantian** [comment]
As of now, I won't look into this issue, because I'm not using Jupyter. If someone looks at this and decides to move forward, please feel free to reopen this issue and comment on some steps or a prototype. I'm not against the idea of making it work on Jupyter.

**Comment by maartenbreddels** [comment]
Example commit https://github.com/maartenbreddels/per4m/commit/d6796cec113f65dc53872480d7ce7dcf1ba40771
