### ISSUE TITLE
log_parse能否支持递归展示函数栈?

### ISSUE THREAD

**Issue by miniyk2012** [gaogaotiantian/viztracer#75]
如下面代码, 我用log_parse想查看hello1的调用, 目前只能看到hello1本身, 看不到hello2的调用, 不知是否可以增加一个--recursive之类的选项, 支持递归查看函数栈. 因为一个常用场景是排查某个函数的调用慢, 如果只能看到hello1而无法看到它所调用的hello2的情况, 则还得给hello2加log_parse,  二分法人工得排查具体哪个函数慢.
```python
from viztracer import log_sparse

def hello2():
    return 'hello2'

@log_sparse
def hello1():
    v = hello2()
    return v + 'hello1'

if __name__ == '__main__':
    hello1()
```
![image](https://user-images.githubusercontent.com/9164258/102865490-c958d480-4470-11eb-9a3f-eb792cc8ee40.png)

**Comment by gaogaotiantian** [comment]
这就是viztracer不加``--log_sparse``的功能啊……``--log_sparse``就是为了不去递归，只看entry设计的。如果你需求整个的调用栈，为什么不直接使用viztracer呢？是冗余信息太多？如果你的程序的运行核心是在调用部分，那别的东西应该不是很多。如果你觉得不容易找到，可以试试``--log_func_exec``去标记函数调用的位置。

当然了，如果你真的是特别需求这种把某个入口为root的标记形势，我可以加一个``@trace``的decorator， 但是实际上基本就是
```
tracer = get_tracer()
tracer.start()
tracer.stop()
```

最后你save一下……

**Comment by miniyk2012** [comment]
(⊙o⊙) 谢谢, 我回去多看看文档
