### ISSUE TITLE
viztracer -m does not set `__name__` correctly

### ISSUE THREAD

**Issue by maartenbreddels** [gaogaotiantian/viztracer#83]
Given this module:
```
# file testm.py
print(__name__)
```

```
$ python -m testm
__main__
$ viztracer --quiet -m testm
testm
```

Python 3.7.8

**Comment by gaogaotiantian** [comment]
The fix is in ``master`` now. I do not plan to come up with an immediate release. If you do need the feature, you could install the ``master`` version.
