### ISSUE TITLE
MPI support

### ISSUE THREAD

**Issue by kllp** [gaogaotiantian/viztracer#95]
With mpi4py you run `mpirun python main.py`
but `mpirun viztracer --log_multiprocess main.py` leads to
`FileNotFoundError: [Errno 2] No such file or directory: '
./viztracer_multiprocess_tmp'`

The command runs multiple viztracer instances and a result.html is generated. 
Can I ignore that error?
What do you think about MPI support?

**Comment by gaogaotiantian** [comment]
There's no way that you can run multiple viztracer instances and let them coordinate with each other automatically without any information. 

Are you trying to run multiple multi-process python programs? I'm not familiar with MPI, is the ``main.py`` program itself multi-process as well?

If ``main.py`` is single process and you achieve parallel process only by using MPI, then what you need is multiple "single-process" reports from each process spawned by MPI and combine them together. VizTracer is able to do this now:
```
# This will instantiate multiple viztracer and each one of them will generate a report with different file names
mpirun viztracer -o result.json --pid_suffix main.py
# This will combine all the json reports together to a result.html file
viztracer --combine result_*.json
```

However, if each VizTracer instance also needs to log a multi-process program, VizTracer is not completely be able to do it yet. In theory it could also be done, but the temporary report folder is fixed for now(``./viztracer_multiprocess_tmp`` as you've seen) so there will be conflicts. 

I can work on an improvement if you need this feature. If you do, could you put up a minimum setup for me to test this?

**Comment by gaogaotiantian** [comment]
Actually, now that I think about it, the multi-multi-process case should be pretty easy to fix, too. I'll do a fix to master later today and hopefully you can try it on your project.

**Comment by gaogaotiantian** [comment]
Okay I checked in a patch in #96 which should make multi-multi-process program work as well. 
```
# This will instantiate multiple viztracer and each one of them will generate a report with different file names
mpirun viztracer --log_multiprocess -o result.json --pid_suffix main.py
# This will combine all the json reports together to a result.html file
viztracer --combine result_*.json
```
You could try this if your ``main.py`` is multi-process program. 

It's not released yet so you'll have to build from source. 
```
pip install git+https://github.com/gaogaotiantian/viztracer
```

**Comment by kllp** [comment]
Great effort of yours! 
It's not a multi-multi-process. 
`mpirun` runs the same program `main.py` as processes on multiple processors. Each processor has a unique number which is called a rank.
In the example below the program flow is different depending on the rank. 

This is a minimal main.py. To test it you have to `pip install mpi4py` and install a MPI library like OpenMPI.
```python
from mpi4py import MPI

comm = MPI.COMM_WORLD
rank = comm.Get_rank()

if rank == 0:
    data = {'a': 7, 'b': 3.14}
    comm.send(data, dest=1, tag=11)
elif rank == 1:
    data = comm.recv(source=0, tag=11)
```

`mpirun viztracer --log_multiprocess -o result.json --pid_suffix main.py`
Before the fix there was a FileNotFoundError and the result file contained multiple threads. 
Now there is no error and there is only a single result.json generated which contains a single thread.

**Comment by kllp** [comment]
It works just fine even with current 0.12 release. Leave out the --log_multiprocess but add the --pid_suffix parameter.
`mpirun viztracer --pid_suffix main.py`

**Comment by gaogaotiantian** [comment]
Yeah, if it's not a multi-multi-process program, I would expect ``--pid_suffix`` should solve the problem. Glad it works for you.
