### ISSUE TITLE
Question: How to visualize output in print quality?

### ISSUE THREAD

**Issue by kllp** [gaogaotiantian/viztracer#97]
chrome://tracing, perfetto.dev and speedscope.app have no image export feature.
Do you know how to get a high quality visualization out of a json trace? 
Screenshots and chrome's print function are blurry.
https://github.com/catapult-project/catapult/issues/4623

**Comment by gaogaotiantian** [comment]
Sorry I don't know how to do it. It's more like a front-end issue. I would imagine a high-res SVG of the FULL trace would be huge.

**Comment by kllp** [comment]
Okay thank you for your quick reply.
